### ISSUE TITLE
startMonitoringForRegion without major and minor

### ISSUE THREAD

**Issue by marcoacierno** [MacKentoch/react-native-beacons-manager#1]
### Version
1.0.1

### Platform
Android

### OS version

android 5.0

### Steps to reproduce
1.  Call startMonitoringForRegion with only identifier and UUID. Example:
```
Beacons.startMonitoringForRegion({
    identifier: 'region',
    uuid: 'MY-UU-ID-HELLO-0001111000',
});
```

### Expected behavior

The app should start monitoring 

### Actual behavior

The app "crashes" with a redbox error and the message: 'TypeError: expected dynamic type 'double' but had type 'null' (constructing arguments for BeaconsANdroidModule.startMonitoring at argument index 2)'

It looks like it doesn't handle well an undefined major/minor in `startMonitoringForRegion`. 

(Note: I'm using react-native-ibeacons but I guess I will have the same problem with this version too?)

**Comment by MacKentoch** [comment]
Hi @marcoacierno 

Thank you for this complete and helpful issue.
*You are right this is exactly the same as `react-native-ibeacons` for this version.*

As `minor` and `major` are **optionals** but the bridge clearly does not handle that.
To be honest I did not even test myself with null major / minor.

I will fix it. 
It can be useful to be able to monitor or range multiple beacons sharing same UUID.

**Comment by MacKentoch** [comment]
Going deeper into monitoring reveals that there is more to be updated.

I suspect it comes from side effects after upgrading altbeacon.
It will take more time than I thought but is is ok.

**Comment by Davidcreador** [comment]
Hello @MacKentoch! I was trying to do the same and it didn't work. :( 
Do you have any update on this? If I can help you with something I'd love to.

**Comment by MacKentoch** [comment]
hi @Davidcreador thank you.
But don't worry I get it working. 
I just need to test a bit more but I'm sure it was just about passing null from React Native to an `int` is not working as expected.

**Comment by MacKentoch** [comment]
Glad to annonce: I've just publish new version v1.0.2 to fix android monitoring with major and minor set as null.

Check [android example](https://github.com/MacKentoch/react-native-beacons-manager/blob/master/examples/BeaconsDemo/index.android.js) that I updated to validate the fix.

Note: monitoring is slow compared to regioning.
In case of leaving event it can take few seconds to trigger.

I don't know if it is expected behaviour but it comes from altbeacon.

Thank you for your feedbacks and issues = precious help!

**Comment by marcoacierno** [comment]
Amazing! Thank you :) I will update my version / try it as soon as I can. ^^ (I guess we can close the issue?)

**Comment by FilipMessa** [comment]
Hi i have same issue with new version v1.0.2  
i try run your example project on Android 6.0.1

**Comment by MacKentoch** [comment]
Hi @FilipMessa I'm sorry I thought it was fixed.

I tested on real device (*it is mandatory*) and mine is a Nexus 5X (*up to date: 7.1.1*).

I doubt it is a matter of android versioning. 
**But** may I ask you a favor to help understanding where should I put more effort to fix it:
> could you try to launch the example [here](https://github.com/MacKentoch/react-native-beacons-manager/tree/master/examples/BeaconsDemo) on the same condition (your device with Android 6.0.1)?

This example is the what I use exactly when working on this library.
It could be nice to compare your experience with your own device.

@marcoacierno I'm affraid we can't close this issue right now... But it is just a matter of time 😄

**Comment by FilipMessa** [comment]
Hi, i have been trying your example, but still same result: 
`TypeError: expected dynamic type 'double' but had type 'null' (constructing arguments for BeaconsANdroidModule.startMonitoring at argument index 2)'`

Device:
ANDROID: 6.0.1
Samsung Galaxy S4 GT-I9505

**Comment by MacKentoch** [comment]
Thank you @FilipMessa for the precious feedback.

I will investigate:
- wether I messed myself when publishing (*why not*)
- or it is related to some kind compatibility between `altbeacon` and `android 6` (*I should find easily an android devices with this version*).

Anyway I will be fixed (not only I maintain this lib but I need it working too).

**Comment by MacKentoch** [comment]
I've tested the example on a 6.0 android: no error BUT nothing working...

So I guess I have to envistigate altbeacon library compatibility.
Things are always far more simple on iOS (yes I come from iOS^^).

**Comment by FilipMessa** [comment]
I understand you iOS is more developer friendly than Android in most cases. Anyway i would like to thank you for your job on this module.

**Comment by MacKentoch** [comment]
@FilipMessa I think I should investigate in this way: [react-native-beacons-android issue with android 6](https://github.com/mmazzarolo/react-native-beacons-android/issues/15).

It seems like it is a matter of Permission.

**Comment by MacKentoch** [comment]
@FilipMessa good news. I made it working on android 6. 

I did so many tests that I need to test from a fresh example to be sure what `is exactly needed for android 6`.

Right now I added `permission in the manifest` and I check in application permission before launching ranging.

**But it seems like you simply just have to `active location service`in addition to `bluetooth service` in android 6.**

#### By the time I check and filter what is needed if by chance you could test by just `activating location service` (no code change at all)?

**Comment by MacKentoch** [comment]
I close the issues that is fixed for a while but had a doubt for android 6 not working (just active location service on android < 7).
