### ISSUE TITLE
NativeModules.BeaconsAndroidModule returns undefined

### ISSUE THREAD

**Issue by MathildeKerhom** [MacKentoch/react-native-beacons-manager#10]
### Version
1.0.1

### Platform
Android

### OS version

android 5.1

### Steps to reproduce
1.  Create a new React-Native App
2.  Import Beacons from 'react-native-beacons-manager'
3.  In the componentWillMount method of index.android.js file call Beacons.detectIBeacons() function

### Expected behavior
App should be able to detect Beacons.

### Actual behavior
Getting "Cannot read property 'addParser' of undefined".

**Comment by MacKentoch** [comment]
Hi @MathildeKerhom 

I suspect altBeacon (library used in native part of android) not to be not compatible with android 5.

Current altBeacon version is : 2.9.2.

The lowest android device I own is android 6.
So it will not help to ensure android 5 compatibility.

**Comment by MathildeKerhom** [comment]
Hi,

Thanks for the quick reply.

I just tried again on an Adroid 6 device using sdk 23 as minSdk and targetSdk in the AndroidManifest and I'm still getting the same error.

**Comment by MacKentoch** [comment]
In some way I prefer that.

Can you update to v1.0.2?

**I fixed it not long time ago, so maybe it was v1.0.2 that fixed it.**

*NOTE: Don't forget to link and when in android 6 (so maybe android 5 too) don't forget to enable bluetooth service + location service.*

**Comment by MacKentoch** [comment]
No more activity so I close this issue.

Feel free to open it back if needed.

**Comment by helloagain-dev** [comment]
I have a similar error.

When I simply import the library like this:

```
import Beacons        from 'react-native-beacons-manager';
```

I get the following error:

```
undefined is not an object (evaluating 'beaconsAndroid.ARMA_RSSI_FILTER')
```

I tried it on an emulator and a Nexus 6P with Android 7.1 with the latest version on github.
Any ideas why this is not working?

**Comment by helloagain-dev** [comment]
My bad, after linking 3 times it worked.

**Comment by berkeguncan** [comment]
i got the same error and it does not working how can i fix it ?

**Comment by sataporn8063** [comment]
> I have a similar error.
> 
> When I simply import the library like this:
> 
> ```
> import Beacons        from 'react-native-beacons-manager';
> ```
> I get the following error:
> 
> ```
> undefined is not an object (evaluating 'beaconsAndroid.ARMA_RSSI_FILTER')
> ```
> I tried it on an emulator and a Nexus 6P with Android 7.1 with the latest version on github.
> Any ideas why this is not working?

How are you solved this problem i can't solve it

**Comment by sataporn8063** [comment]
after i run this cmd react-native link
