### ISSUE TITLE
How to detect iBeacons on array regions?

### ISSUE THREAD

**Issue by longpro1601** [MacKentoch/react-native-beacons-manager#102]
### Version
1.0.7

### Platform
Android

### OS version

 android 7.0...

###Actual behavior
I have a array regions:
const regions =[ 
{
    identifier: 'Estimotes_1',
    uuid: 'uuid_1'
},
{
    identifier: 'Estimotes_2',
    uuid: 'uuid_2'
},
{
    identifier: 'Estimotes_3',
    uuid: 'uuid_3'
},
]

How to detect iBeacons on array regions?
I tried but not work.
Beacons.startRangingBeaconsInRegion(regions[0]);
Beacons.startRangingBeaconsInRegion(regions[1]);
Beacons.startRangingBeaconsInRegion(regions[2]);

**Comment by bezblue** [comment]
how to?
