### ISSUE TITLE
Does not work with targetSdkVersion 25+ in Android

### ISSUE THREAD

**Issue by bab00n87** [MacKentoch/react-native-beacons-manager#104]
### Version
1.0.7

### Platform
iOS | Android

### OS version

android 7.0...

Hey guys I have a problem with SDK 25+. When I change my targetSKDVersion for my application to 25 
then my phone does not find any beacon in range. 
When I change it back to 22, everything works fine.

D/BeaconsAndroidModule: rangingConsumer didRangeBeaconsInRegion, beacons: []

This is basically the only thing I get.

regards florian

**Comment by akshaypm** [comment]
Same happens in my case... everything works fine in debug mode but when debug is disabled then phone does not find any beacons or receive packets from beacons and the same happens when generated a release apk

**Comment by empitechathu** [comment]
I am having the same problem here .. I am using SDK version 26.0.0 for android and it's not working at all .. IOS is working fine. I cant downgrade my SDK version because of other packages I am using require the latest SDK. I think this is an issue from this package. Can someone please look into this and give an update for this issue.

**Comment by thon0112** [comment]
@empitechathu , I am facing the same issue. Do you have any alternative solution

**Comment by Yara-the-devil-princess** [comment]
Thank you..Can you suggest some other modules or npm package.. Actually
beacon will detect on foreground...when my app is move to background
...within few seconds it will not able to detect beacons Can anyone prefer
me ..my app is detect the beacon when my app is in killed state and
background..

**Comment by bovyKasorn** [comment]
Add PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION it work for me (targetSdkVersion 26)

**Comment by Samykills** [comment]
@soundaryad10  try invoking it using a worker thread, that way u can run your task in the background

**Comment by soundaryad10** [comment]
I need to ranging my beacons when my app is killed ..i need to send
notification when new beacons is detected when my app is killed. Can you
help me to provide me any way to proceed further.

**Comment by Pacn91** [comment]
Hi, 
I'm having the same problem: can't detect any beacon. I'm using the targetSKDVersion 26 and I also put in my code `PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION` but with no success. Here is my code:
`componentWillMount() {
    PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION;

    if(Platform.OS === 'android'){
      PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION;
      Beacons.detectIBeacons();
      Beacons
        .startRangingBeaconsInRegion({identifier: 'Tomar', uuid:null})
        .then(() => console.log('Beacons ranging started succesfully'))
        .catch(error => console.log(`Beacons ranging not started, error: ${error}`));
    }
}

componentDidMount(){
DeviceEventEmitter.addListener('beaconsDidRange',(data) => {
          console.log("Beacons found:", data.beacons);
}`

Am I doing something wrong?
Thank you!

**Comment by bab00n87** [comment]
I solved it my problem.

Completely forgot about that you need an extra permission in Android 8.0 (like iPhone). AndroidPermissions.

Added this to my code.

import { PermissionsAndroid } from 'react-native';

export const requestFineLocationPermission = async () => {
  try {
    const granted = await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
      {
        'title': 'Beacon',
        'message': 'The Application needs Access to your Bluetooth ' +
          'to Track Beacons.'
      }
    )
    if (granted === PermissionsAndroid.RESULTS.GRANTED) {
      console.log("You can use the system")
    } else {
      console.log("Beacon Tracking Denied")
    }
  } catch (err) {
    console.warn(err)
  }
}


  componentDidMount = () => {
    requestFineLocationPermission()
  };


But be aware, the Permission Modal only appears if you have the right stuff in the manifest. In my case like this:

    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>

**Comment by Pacn91** [comment]
@bab00n87 thank you so much! That works :D
