### ISSUE TITLE
Help with triggering a function on beacon detection?

### ISSUE THREAD

**Issue by edencakir** [MacKentoch/react-native-beacons-manager#11]
Sorry if this is a silly one, how can I execute a http request for example, when a beacon is detected in the background mode?

**Comment by MacKentoch** [comment]
Hi @edencakir 

It is not silly at all but nice question.

First I would say it depends on the platform (iOS and android).

I did not have a try of using/testing background modes, maybe there is a react native bridge that would help.

In iOS world I would add in `didFinishLaunchingWithOptions:(NSDictionary *)launchOptions delegate` (*called when app is in background*):
```objectiveC
  // a location event detected:
  if([launchOptions objectForKey:@"UIApplicationLaunchOptionsLocationKey"])
  {
    // here is your code to handle detection in native or submit information to react-native via some kind of bridge
  }
```

I may create an example later for that.

But right now so many things to finish in this library (a bit young).

**Comment by edencakir** [comment]
@MacKentoch Thanks for the reply, looking forward to it 👍
