### ISSUE TITLE
🔥🔥🔥 PUBLISH LATEST VERSION!!!

### ISSUE THREAD

**Issue by retyui** [MacKentoch/react-native-beacons-manager#113]
### Version
1.0.7

### Platform
Both

### OS version
Any

### Steps to reproduce
1.  Got to [npm/react-native-beacons-manager](https://www.npmjs.com/package/react-native-beacons-manager)
2.  Open tab `Versions`
3.  Сompare latest version (now is `1.0.7`)
![image](https://user-images.githubusercontent.com/4661784/46468414-09bcd100-c7d9-11e8-86c2-c110937ffd38.png)

### Expected behavior
I want to see latest version `1.1.0`
![image](https://user-images.githubusercontent.com/4661784/46468573-733cdf80-c7d9-11e8-9520-5fcbeb1195e3.png)

### Actual behavior
But I see latest version `1.0.7`

**Comment by retyui** [comment]
rel https://github.com/MacKentoch/react-native-beacons-manager/issues/103

**Comment by MacKentoch** [comment]
duplicate #103
