### ISSUE TITLE
 ERROR await is a reserved word 

### ISSUE THREAD

**Issue by BrenerInn** [MacKentoch/react-native-beacons-manager#115]
Hi! Im new on beacons an a little bit new on react native.

I just try the Example of the library a got this error:  await is a reserved word 

This is the code i use:

import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { DeviceEventEmitter } from 'react-native'
import Beacons from 'react-native-beacons-manager'

Beacons.detectIBeacons() 

try {
  await Beacons.startRangingBeaconsInRegion('REGION1')
  console.log(`Beacons ranging started succesfully!`)
} catch (err) {
  console.log(`Beacons ranging not started, error: ${error}`)
}

DeviceEventEmitter.addListener('beaconsDidRange', (data) => {
  console.log('Found beacons!', data.beacons)
})

export default class App extends React.Component {
  render() {
   

    return (
  
    
      
    
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

I try inside the render and is the same.. Can someone helpme to know what im do it wrong?
 Thanks!

**Comment by BrenerInn** [comment]
I just leave the Beacons.detectIBeacons() and got an Unexpected Token error

**Comment by MacKentoch** [comment]
Hi, `await is a reserved word` is a typical error when you did not specify the surrounding function is `async`.

Ensure using await in an async function like:
```js
async dummy() {
 await myAsyncProcess();
}
```

NOTE: even a callback function needs to be prefixed by async if you wanna use `await` inside.

**Comment by MacKentoch** [comment]
This a javascript issue and not related to this librairie nor React-Native (that contains all babel plugins for async/await).

I close this issue.
