### ISSUE TITLE
ranging beacons events differ from Android to iOS

### ISSUE THREAD

**Issue by r-bansal** [MacKentoch/react-native-beacons-manager#12]
### Version
1.0.1

### Platform
iOS | Android

### OS version
iOS 10| android 7.0...
android 7 - most likely all Android versions

### Steps to reproduce
1.  range for beacons on iOS and Android
2.  iOS returns consistent `beacons` arrays
3.  Android returns inconsistent `beacons` array where sometimes the beacon is shown in the array and sometimes it is not.

### Expected behavior
Consistent between iOS and Android

### Actual behavior
Inconsistente between iOS and Android

Most likely a lower level issue related to the frequency of receiving the messages and confirming that the beacon exists after 3-5 successful fires and same for a beacon not existing. Maybe a nice to have.

I rarely notice this on iOS (testing with three beacons), and all of them fire consistently, where on Android I may see 0, 1, 2, or 3 (rarely) fire.

**Comment by MacKentoch** [comment]
Thank you @r-bansal 

**Really important to keep track of this issue.**

I had the **feeling** (*did not have time to compare both in same time*) android was not as `accurate`, `consistent` (*you choose a better word*) as iOS.

I try to keep an eye (*from high level since don't have enough the time right now*) on [altbeacon](https://github.com/AltBeacon/android-beacon-library) since it is active repository.

**Comment by eduplus** [comment]
Android devices have a huge range how good they are scanning beacons. I have done tests with different devices. 100 scans and see how many time a beacon was shown. Best ones gave like 96 times, worst were only 7! Beacon sending signal and client scan rate also affect this.

I don't think there is so much this library can do about that. If it is messing up your use case, what you can do is do some sort of noise filtering algorithm on top of beacon ranging results.

**Comment by MacKentoch** [comment]
Really interesting @eduplus 

Now you've shared your experience I remember that my cheap android device (*for testing android 6*) is really bad compared to my Nexus5x (*not a flagship but already nice hardware*) with this [beacon simulator](https://play.google.com/store/apps/details?id=net.alea.beaconsimulator&hl=fr)

So I clearly share your point of view.

**Comment by MacKentoch** [comment]
As it seems more related to hardware I close this issue.
