### ISSUE TITLE
Android App crashing when method startRangingBeaconsInRegion is called

### ISSUE THREAD

**Issue by Pacn91** [MacKentoch/react-native-beacons-manager#121]
### Version
1.0.7

### Platform
Android

### Actual behavior
App is crashing after some seconds or when it detects a beacon (even when I don't have any event defined yet). I just have this in my `componentDidMount`: 
```
if(Platform.OS === 'android'){
      Beacons.detectIBeacons();
      Beacons
        .startRangingBeaconsInRegion( 'xpto')
        .then(() => console.log('Beacons ranging started succesfully'))
        .catch(error => console.log(`Beacons ranging not started, error: ${error}`));
}
```
This is caused by the method `startRangingBeaconsInRegion`. I'm getting this error:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.altbeacon.beacon.Identifier.toString()' on a null object reference
	at com.mackentoch.beaconsandroid.BeaconsAndroidModule.createMonitoringResponse(BeaconsAndroidModule.java:233)
	at com.mackentoch.beaconsandroid.BeaconsAndroidModule.access$100(BeaconsAndroidModule.java:37)
	at com.mackentoch.beaconsandroid.BeaconsAndroidModule$1.didExitRegion(BeaconsAndroidModule.java:221)
	at org.altbeacon.beacon.BeaconIntentProcessor.onHandleIntent(BeaconIntentProcessor.java:90)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:173)
	at android.os.HandlerThread.run(HandlerThread.java:65)
```

Hope you can help me. Thank you!

**Comment by Pacn91** [comment]
The thing is: I need to have UUID as null. I've tried already like this: 
`Beacons.startRangingBeaconsInRegion({identifier: "XPTO", uuid: null})`

Also tried with a defined UUID and I still got the same problem.

**Comment by Spencer-Yoder** [comment]
You could try running the newest version of Beacons-manager using `npm install MacKentoch/react-native-beacons-manager`. This will install it off of master on github. You have to re-link the project once it is done, and reinstall after you install any other packages.

**Comment by Pacn91** [comment]
@Spencer-Yoder thank you for the help. Unfortunately I'm getting this error after installing and re-linking like you said:

![screenshot_2018-11-27-16-35-19-732_com movtour](https://user-images.githubusercontent.com/17788348/49096912-8a410080-f263-11e8-869d-fc5be9510a77.png)

Do you know what this is? Thank you

**Comment by Pacn91** [comment]
I end up solving this issue by following this: https://github.com/nuonic/react-native-beacons-manager/commit/61e8f5b6f161f29e44c1cd75208d40d021d3b496
