### ISSUE TITLE
data.beacons is returning as an empy array. I can't get Distance and Proximity. 

### ISSUE THREAD

**Issue by avidavis** [MacKentoch/react-native-beacons-manager#125]
### Version
1.0.1

### Platform
Android

### OS version
android 7.0...

### Steps to reproduce
1.   Here is my component code 
/**
 * @flow
 */
`
 import` React, { Component } from 'react';
import { DeviceEventEmitter } from 'react-native'
import {
  StyleSheet,
  Text,
  ListView,
  View,
} from 'react-native';
import Beacons from 'react-native-beacons-manager';

export default class BeaconsComp extends Component {
  // will be set as a reference to "beaconsDidRange" event:
  beaconsDidRangeEvent = null;

  state = {
    // region information. Replace UUID and UUID2 with your own beacon region information. 
    uuid: '6665542b-41a1-5e00-931c-6a82db9b78c3',
    identifier: 'Stage Right Exit',
    uuid2: '6665542b-41a1-5e00-931c-6a82db9b78c2',
    identifier2: 'Stage Left Exit',
    rangingDataSource: new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2}).cloneWithRows([]),
    rangingDataSource2: new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2}).cloneWithRows([])
  };

 async componentWillMount(){
   const { identifier, uuid, identifier2, uuid2 } = this.state;
   const FestivalExit1 = { identifier, uuid };
   const FestivalExit2 = { identifier: identifier2, uuid: uuid2 }; 

   // start iBeacon detection
   await Beacons.detectIBeacons();

   // Range beacons inside the different regions
   await Beacons
   .startRangingBeaconsInRegion(FestivalExit1) // or like  < v1.0.7: .startRangingBeaconsInRegion(identifier, uuid)
   .then(() => console.log('FestivalExit1 ranging started succesfully'))
   .catch(error => console.log(`FestivalExit1 ranging not started, error: ${error}`));

   await Beacons
   .startRangingBeaconsInRegion(FestivalExit2) // or like  < v1.0.7: .startRangingBeaconsInRegion(identifier, uuid)
   .then(() => console.log('FestivalExit2 ranging started succesfully'))
   .catch(error => console.log(`FestivalExit2 ranging not started, error: ${error}`));
}

async componentDidMount() {
   // Print a log of the detected iBeacons (1 per second)

// Print a log of the detected iBeacons (1 per second)
await DeviceEventEmitter.addListener('beaconsDidRange', (data) => {
  console.log('Found beacons!', data)
})
  const { identifier, identifier2 } = this.state;
   this.beaconsDidRangeEvent = Beacons.BeaconsEventEmitter.addListener(
     'beaconsDidRange',
     (data) => {
       if (data.beacons[0] !== null || undefined) {
         Object.assign(data.beacons[0], {identifier: data.identifier});
       }

       switch (data.identifier) {
         case identifier:
           console.log(identifier)
           this.setState({ rangingDataSource: this.state.rangingDataSource.cloneWithRows(data.beacons) });
           break;
         case identifier2:
          console.log(identifier2);
          this.setState({ rangingDataSource2: this.state.rangingDataSource2.cloneWithRows(data.beacons) });
          break;
         default:
          console.log('error: check your identifiers!')
           break;
       }
    }
  );
 }

 render() {
   const { rangingDataSource } =  this.state;
   const { rangingDataSource2 } =  this.state;

   return (
     <View style={styles.container}>
       <Text style={styles.headline}>
         ranging beacons in the area:
       </Text>
       <ListView
         dataSource={ rangingDataSource }
         enableEmptySections={ true }
         renderRow={this.renderRangingRow}
       />
          <ListView
         dataSource={ rangingDataSource2 }
         enableEmptySections={ true }
         renderRow={this.renderRangingRow}
       />
      </View>
   );
 }

 renderRangingRow = (rowData) => {
   return (
     <View style={styles.container}>
       <View style={styles.column}>
       <Text>
         Identifier:{rowData.identifier}
       </Text>
       <Text>
         UUID: {rowData.uuid ? rowData.uuid  : 'NA'}
       </Text>
       </View>
       <View style={styles.row}>
       <Text style={styles.smallText}>
         Major: {rowData.major ? rowData.major : 'NA'}
       </Text>
       <Text style={styles.smallText}>
         Minor: {rowData.minor ? rowData.minor : 'NA'}
       </Text>
       <Text style={styles.smallText}>
         RSSI: {rowData.rssi ? rowData.rssi : 'NA'}
       </Text>
       </View>
       <View style={styles.column}>
       <Text>
         Proximity: {rowData.proximity ? rowData.proximity : 'NA'}
       </Text>
       <Text>
         Distance: {rowData.distance ? rowData.distance.toFixed(2) : 'NA'}
       </Text>
       </View>
     </View>
   );
 }
}

const styles = StyleSheet.create({
  container: {
    marginTop: 10,
    paddingRight: 5,
    paddingLeft: 5,
    marginBottom: 5,
  },
  headline: {
    fontSize: 20,
    marginHorizontal: 5,
  },
  column: {
    flexDirection: 'column',
    paddingLeft: 8,
    paddingBottom: 5,
  },
  row: {
    flexDirection: 'row',
    paddingLeft: 8,
    paddingBottom: 5,
  },
  iconContainer: {
    flexDirection: 'column',
    marginRight: 10,
  },
  infoContainer: {
    flex: 1,
    flexDirection: 'column',
  },
  majorMinorContainer: {
    flexDirection: 'row',
  },
  smallText: {
    marginRight: 15,
  },
  actionsContainer: {
    marginVertical: 10,
    marginHorizontal: 5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  actionButton: {
    width: 160,
    backgroundColor: '#A6A6A6',
    paddingHorizontal: 5,
    paddingVertical: 10,
  },
  actionText: {
    alignSelf: 'center',
    fontSize: 11,
    color: '#000000',
  },
});
`
2.  Here is my package.json file. 
` "dependencies": {
    "axios": "^0.18.0",
    "lodash": "^4.17.11",
    "native-base": "^2.8.0",
    "react": "16.5.0",
    "react-native": "0.57.1",
    "react-native-beacons-manager": "git+https://github.com/MacKentoch/react-native-beacons-manager.git",
    "react-native-vector-icons": "^5.0.0",
    "redux": "^4.0.1",
    "react-redux": "^5.1.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.45.6",
    "react-test-renderer": "16.5.0",
    "remote-redux-devtools": "^0.5.13"
  },
  "jest": {
    "preset": "react-native"
  }
}
`
### Expected behavior

beacons: Array(0)    <--------------------- THIS SHOULD CONTAIN A OBJECT THAT HAS DISTANCE AND PROXIMITY RSSI MINOR AND MAJOR DATA IN IT. 

{beacons: Array(0), uuid: "6665542b-41a1-5e00-931c-6a82db9b78c3", identifier: "Stage Right Exit"}
beacons: Array(0)    <--------------------- 
length: 0
__proto__: Array(0)
identifier: "Stage Right Exit"
uuid: "6665542b-41a1-5e00-931c-6a82db9b78c3"
__proto__: Object

### Actual behavior
beacons: Array(0)    <--------------------- THIS RETURNS WITH AN EMPTY ARRAY.  

SCREENSHOT
<img width="551" alt="samsung-sm-g928v 2019-01-07 15-11-25" src="https://user-images.githubusercontent.com/34724557/50799382-9c658400-1290-11e9-9064-1d644dd73028.png">

**Comment by lkdbach** [comment]
Do you use Beacon Simulator or real beacon device to broadcast BLE signal? @avidavis

**Comment by lkdbach** [comment]
I have same issue like you when implementing for android version. I'm using Beacon Simulator app on Android to broadcast BLE

**Comment by avidavis** [comment]
@lkdbach  I am using a iBKS105 Beacon not a simulator. When I used the example version using 

This packages.json
https://github.com/MacKentoch/react-native-beacons-manager/blob/master/package.json

 this.beaconsDidRangeEvent = Beacons.BeaconsEventEmitter.addListener(
  'beaconsDidRange',
  (data) => {
  console.log('beaconsDidRange data: ', data);  // This returned the beacons array with Proximity and Distance.

The issue is the I need to integrate with the newest version of React Native in order to utilize this in actuality.

**Comment by avidavis** [comment]
@lkdbach  CORRECTION: I gave you the wrong link.

I used this packages.json  from the examples directory of this repo I originally put the main repo's packges.json. 

https://github.com/MacKentoch/react-native-beacons-manager/blob/master/examples/BeaconsDemo/package.json  // This packages.json 

With the following component it returned the beacons array with data in it like Proximity and Distance. 

` /**
 * @flow
 */
import React from 'react';
import Beacons from 'react-native-beacons-manager';

export default class BeaconsComp extends Component {
  // will be set as a reference to "beaconsDidRange" event:
  beaconsDidRangeEvent = null;

  state = {
    // region information. Replace UUID and with your own beacon region information. 
    uuid: '6665542b-41a1-5e00-931c-6a82db9b78c1',
    identifier: 'TEST BEACON 1',
    rangingDataSource: new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2}).cloneWithRows([]),
  };

 componentWillMount(){
   const { identifier, uuid} = this.state;
   const FBeacons = { identifier, uuid };
   // start iBeacon detection
   Beacons.detectIBeacons();


   // Range beacons inside the different regions
   Beacons
   .startRangingBeaconsInRegion(FBeacons) // or like  < v1.0.7: .startRangingBeaconsInRegion(identifier, uuid)
   .then(() => console.log('Beacons ranging started succesfully'))
   .catch(error => console.log(`Beacons ranging not started, error: ${error}`));
 }

 componentDidMount() {
   this.beaconsDidRangeEvent = Beacons.BeaconsEventEmitter.addListener(
     'beaconsDidRange',
     (data) => {
       if (data.beacons[0] !== null || undefined) {
         Object.assign(data.beacons[0], {identifier: data.identifier});
       }
        console.log(`////////////////////////////////`);
              console.log(`Beacon Data:`);
       console.log(`Identifer: ${data.identifier}`);
       console.log(`UIDD:  ${data.uuid}`);
       console.log(`Proximity:  ${data.beacons[0].proximity}`);
       console.log(`Distance:  ${data.beacons[0].distance}`);
       console.log(`RSSI:  ${data.beacons[0].rssi}`);
       console.log(`Minor:  ${data.beacons[0].minor}`);
       console.log(`Major:  ${data.beacons[0].major}`);
      console.log(`////////////////////////////////`);
      this.setState({ rangingDataSource: this.state.rangingDataSource.cloneWithRows(data.beacons) });
     }
   );
 }

 render() {
   const { rangingDataSource } =  this.state;

   return (
     <View style={styles.container}>
       <Text style={styles.headline}>
         ranging beacons in the area:
       </Text>
       <ListView
         dataSource={ rangingDataSource }
         enableEmptySections={ true }
         renderRow={this.renderRangingRow}
       />
          <ListView
         dataSource={ rangingDataSource2 }
         enableEmptySections={ true }
         renderRow={this.renderRangingRow}
       />
      </View>
   );
 }

 renderRangingRow = (rowData) => {
   return (
     <View style={styles.container}>
       <View style={styles.column}>
       <Text>
         Identifier:{rowData.identifier}
       </Text>
       <Text>
         UUID: {rowData.uuid ? rowData.uuid  : 'NA'}
       </Text>
       </View>
       <View style={styles.row}>
       <Text style={styles.smallText}>
         Major: {rowData.major ? rowData.major : 'NA'}
       </Text>
       <Text style={styles.smallText}>
         Minor: {rowData.minor ? rowData.minor : 'NA'}
       </Text>
       <Text style={styles.smallText}>
         RSSI: {rowData.rssi ? rowData.rssi : 'NA'}
       </Text>
       </View>
       <View style={styles.column}>
       <Text>
         Proximity: {rowData.proximity ? rowData.proximity : 'NA'}
       </Text>
       <Text>
         Distance: {rowData.distance ? rowData.distance.toFixed(2) : 'NA'}
       </Text>
       </View>
     </View>
   );
 }
}

`

**Comment by lkdbach** [comment]
I confirm that it work on 
"react": "16.4.1", "react-native": "0.55.4"

**Comment by lkdbach** [comment]
This issue is not related to react and react-native version, it do not make sense

**Comment by avidavis** [comment]
@lkdbach can you share your package.json. thanks

**Comment by lkdbach** [comment]
{
  "name": "test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "android": "adb uninstall \"com.test\" ; react-native run-android",
    "ios": "react-native run-ios",
    "ios-release": "react-native run-ios --configuration Release",
    "android-release": "adb uninstall \"com.test\" ; react-native run-android --variant=release"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "./app/assets/fonts/"
    ]
  },
  "dependencies": {
    "axios": "^0.18.0",
    "crypto-js": "^3.1.9-1",
    "humps": "^2.0.1",
    "immutable": "3.8.1",
    "lodash": "^4.17.10",
    "metro-bundler": "0.22.1",
    "moment": "^2.22.2",
    "prop-types": "^15.6.2",
    "query-string": "^6.2.0",
    "react": "16.4.1",
    "react-native": "0.55.4",
    "react-native-beacons-manager": "MacKentoch/react-native-beacons-manager",
    "react-native-datepicker": "^1.7.2",
    "react-native-device-info": "^0.24.0",
    "react-native-elements": "^0.19.1",
    "react-native-firebase": "4.3.8",
    "react-native-image-picker": "^0.27.1",
    "react-native-keyboard-aware-scroll-view": "^0.7.2",
    "react-native-modal-datetime-picker": "^6.0.0",
    "react-native-modal-dropdown": "^0.6.2",
    "react-native-qrcode": "^0.2.7",
    "react-native-side-menu": "^1.1.3",
    "react-native-vector-icons": "4.6.0",
    "react-native-view-shot": "^2.4.0",
    "react-navigation": "^2.5.5",
    "react-redux": "5.0.7",
    "redux": "4.0.0",
    "redux-persist": "^4.10.1",
    "redux-persist-transform-immutable": "4.3.0",
    "redux-saga": "0.16.0"
  },
  "devDependencies": {
    "babel-jest": "22.4.4",
    "babel-preset-react-native": "4.0.0",
    "jest": "21.2.1",
    "react-test-renderer": "16.0.0",
    "redux-devtools-extension": "^2.13.5"
  }
}

**Comment by avidavis** [comment]
@lkdbach and your JS file you got to return that data from. Thanks

**Comment by lkdbach** [comment]
Beacons.detectIBeacons();

Beacons
        .startRangingBeaconsInRegion("Weiss Locks")
        .then(() => console.log('Beacons monitoring started successfully'))
        .catch(error => console.log(`Beacons monitoring not started, error: ${error}`));

this.beaconsDidRangeEvent = Beacons.BeaconsEventEmitter.addListener(
        "beaconsDidRange",
        data => {
          console.log('1111', data);
        }
      );

**Comment by avidavis** [comment]
@lkdbach  So, just to make sure it wasn't anything else. I created a fresh react native project using 
react-native init  beacontest

I downgraded the react and react-native version to 
    "react": "16.4.1",
    "react-native": "0.55.4",
    "react-native-beacons-manager": "^1.0.7",
    "react-native-vector-icons": "^6.1.0"

Full package.json
https://github.com/avidavis/React-Native-Beacon-Manager-Boiler-Plate/blob/master/package.json

JS file
https://github.com/avidavis/React-Native-Beacon-Manager-Boiler-Plate/blob/master/App.js

This is the error. 
<img width="886" alt="screen shot 2019-01-09 at 4 18 59 pm" src="https://user-images.githubusercontent.com/34724557/50938239-33b30e80-142c-11e9-81a4-45e0c1426459.png">

**Comment by lkdbach** [comment]
react-native-beacons-manager": "MacKentoch/react-native-beacons-manager",

**Comment by lkdbach** [comment]
Change your beacons manager like that in package.json file

**Comment by avidavis** [comment]
@lkdbach  Like this it still returns the same error as in my screenshot. 
package.json
https://github.com/avidavis/React-Native-Beacon-Manager-Boiler-Plate/blob/master/package.json

**Comment by avidavis** [comment]
@lkdbach I got it to the point where I was using react-native 57  with your RN v55 example on a fresh React Native project and still beacon: []   <------- Empty beacons array.

<img width="544" alt="screen shot 2019-01-09 at 5 06 40 pm" src="https://user-images.githubusercontent.com/34724557/50939340-3f550400-1431-11e9-84af-ada86f9f08a3.png">

**Comment by lkdbach** [comment]
Check your beacon signal type,  eddystone or ibeacon?  RN version is not a problem here.  This lib using native code so it should be not related to your issue

**Comment by avidavis** [comment]
Still nothing. 
<img width="532" alt="screen shot 2019-01-09 at 5 48 14 pm" src="https://user-images.githubusercontent.com/34724557/50940717-e7210080-1436-11e9-8b55-093a3f1b7af8.png">

![screenshot_20190109-174842](https://user-images.githubusercontent.com/34724557/50940728-f56f1c80-1436-11e9-9e84-fb035edaab24.png)

**Comment by lkdbach** [comment]
Replace start ranging function with the following code:
Beacons
.startRangingBeaconsInRegion("test")
.then(() => console.log('Beacons monitoring started successfully'))
.catch(error => console.log(Beacons monitoring not started, error: ${error}));

**Comment by avidavis** [comment]
@lkdbach Thanks man that is weird it seems to be working now. Thanks

**Comment by pratius** [comment]
@avidavis I'm facing the same issues. Could you please advise me what am I missing? I have attached the screenshots for your reference.
<img width="1387" alt="Screen Shot 2022-02-25 at 2 16 54 AM" src="https://user-images.githubusercontent.com/15229476/155617010-3437163a-528d-4db4-a409-6b69c27bf54d.png">
<img width="1430" alt="Screen Shot 2022-02-25 at 2 17 21 AM" src="https://user-images.githubusercontent.com/15229476/155617024-6f817239-3631-4862-bfd4-d5a458625dfc.png">

**Comment by gigflex** [comment]
@pratius 

are you able to make it work?

**Comment by akanksha-ingle** [comment]
@lkdbach,  I'm facing same issue in Android only, getting Distance & Proximity in iOS.
here is my code:

            try {
                Beacons.detectIBeacons();
                Beacons.detectAltBeacons();
                Beacons.detectEstimotes();
                Beacons.detectEddystoneUID();
                Beacons.detectEddystoneTLM();
                Beacons.detectEddystoneURL();

                Beacons.startRangingBeaconsInRegion(region.identifier, region.uuid)
                    .then(() => console.log('232 Beacon startRangingBeaconsInRegion started successfully', region))
                    .catch(error => console.log('24 Error startRangingBeaconsInRegion: ', error));

            } catch (err) {
                console.log(`Beacons ranging not started, error: ${err}`)
            }
            
            
            
                    // Ranging: Listen for beacon changes
        this.beaconsDidRangeEvent = Beacons.BeaconsEventEmitter.addListener(
            'beaconsDidRange',
            data => {
                console.log('beaconsDidRange, data: ', data);

            },
        );

        // monitoring events
        this.regionDidEnterEvent = Beacons.BeaconsEventEmitter.addListener(
            'regionDidEnter',
            ({ uuid, identifier }) => {
                console.log('regionDidEnter, data: ', { uuid, identifier });


            },
        );

        this.regionDidExitEvent = Beacons.BeaconsEventEmitter.addListener(
            'regionDidExit',
            ({ identifier, uuid, minor, major }) => {
                this.setState({ message: 'regionDidExit event' });
                console.log('regionDidExit, data: ', {
                    identifier,
                    uuid,
                    minor,
                    major,
                });

            },
        );
   
   Already tried -
   Beacons.startRangingBeaconsInRegion(region)
   Beacons.startRangingBeaconsInRegion('Estimotes')     
        
![Screenshot 2024-05-16 at 12 34 11 PM](https://github.com/MacKentoch/react-native-beacons-manager/assets/144016320/606bdc53-2846-490c-865e-74519f638e48)
![Screenshot 2024-05-16 at 12 34 25 PM](https://github.com/MacKentoch/react-native-beacons-manager/assets/144016320/c552457d-0e01-47fd-8edf-ecc25b14ba16)
![Screenshot 2024-05-16 at 12 34 59 PM](https://github.com/MacKentoch/react-native-beacons-manager/assets/144016320/1644dd44-41b3-4919-882f-c6a138035811)

**Comment by akankshaingle** [comment]
**UPDATE:** Here is working code-

export const startDetectingBeacons = async () => {
    const region = {
        identifier: 'Estimotes',
        uuid: YourBeaconUUID
    };

    try {
        if (Platform.OS === 'ios') {
            // iOS specific code
            await Beacons.requestAlwaysAuthorization();
            Beacons.startUpdatingLocation();
        } else {
            // Android specific code
            Beacons.detectIBeacons();
            Beacons.detectAltBeacons();
            Beacons.detectEstimotes();
            Beacons.detectEddystoneUID();
            Beacons.detectEddystoneTLM();
            Beacons.detectEddystoneURL();
        }

        // Common code for both platforms
        await Promise.all([
            Beacons.startMonitoringForRegion(region),
            Beacons.startRangingBeaconsInRegion(region)
        ]);

        console.log('Beacons monitoring and ranging started successfully');
    } catch (error) {
        console.error(`Beacons monitoring and ranging not started, error: ${error}`);
    }

    // Ranging: Listen for beacon changes
    const beaconsDidRangeEvent = Beacons.BeaconsEventEmitter.addListener(
        'beaconsDidRange',
        data => {
            console.log('beaconsDidRange, data: ', data);
        },
    );

    // Monitoring events
    const regionDidEnterEvent = Beacons.BeaconsEventEmitter.addListener(
        'regionDidEnter',
        ({ uuid, identifier }) => {
            console.log('regionDidEnter, data: ', { uuid, identifier });
        },
    );

    const regionDidExitEvent = Beacons.BeaconsEventEmitter.addListener(
        'regionDidExit',
        ({ identifier, uuid, minor, major }) => {
            console.log('regionDidExit, data: ', {
                identifier,
                uuid,
                minor,
                major,
            });
        },
    );

    return { beaconsDidRangeEvent, regionDidEnterEvent, regionDidExitEvent };
};

**And make sure to ask all permission before you start detecting beacon.**

if (Platform.OS === 'android') {
  const permissions =
    Platform.Version >= 31
      ? [
        PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
        PermissionsAndroid.PERMISSIONS.BLUETOOTH_SCAN,
        PermissionsAndroid.PERMISSIONS.BLUETOOTH_CONNECT,
      ]
      : [
        PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
        PermissionsAndroid.PERMISSIONS.BLUETOOTH,
      ];

  const granted = await PermissionsAndroid.requestMultiple(permissions);
} else {
  const locationResult = await request(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE);
  const bluetoothResult = await request(PERMISSIONS.IOS.BLUETOOTH_PERIPHERAL);
  const bluetoothStatus = await BluetoothStatus.state();

  console.log('iOS permissions results:', { locationResult, bluetoothResult, bluetoothStatus });
}
