### ISSUE TITLE
null is not an object ('evaluating BeaconsManager.ARMA_RSSI_FILTER')

### ISSUE THREAD

**Issue by sourabhmisal** [MacKentoch/react-native-beacons-manager#129]
![screenshot_2019-02-18-22-36-28-884_com direkt](https://user-images.githubusercontent.com/23289685/52966891-74f4f180-33ce-11e9-9fd9-25d4c1ef93e0.png)

Please help me solve this issue
this app is for my final year project
i like react-native but i am getting so much errors
i am new to react-native

 React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
      Memory: 2.65 GB / 11.85 GB
    Binaries:
      Yarn: 1.13.0 - C:\Users\soura\AppData\Roaming\npm\yarn.CMD
      npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5264788

My app.js code : (same as that of MacKentoch's reactNativeBeaconExample's index.android.js )

**Comment by sourabhmisal** [comment]
resolved it by replacing 
implementation "com.facebook.react:react-native:+" 
to 
implementation "com.facebook.react:react-native:0.58.6" 
in  android/app/build.gradle

**Comment by hadpro24** [comment]
> resolved it by replacing
> implementation "com.facebook.react:react-native:+"
> to
> implementation "com.facebook.react:react-native:0.58.6"
> in android/app/build.gradle

0.58.6 is my version react native or what ? It's don't work for me

**Comment by sourabhmisal** [comment]
Whichever react version you are working on , enter it `implementation "com.facebook.react:react-native:0.58.6"` in android/app/build.gradle file location, hope this helps, as it has been a long time using it
