### ISSUE TITLE
regionDidEnter not firing if the device is already close to beacon when App starts

### ISSUE THREAD

**Issue by nunobasto** [MacKentoch/react-native-beacons-manager#132]
### Version
1.0.7

### Platform
iOS | Android

### OS version
iOS 12.1.1| android 8.0

### Steps to reproduce
1.  Get close to beacon
2.  Open the App for the first time
3.  regionDidEnter does not fire

(if I turn off beacon and turn it on again, then regionDidEnter is fired)

### Expected behavior
regionDidEnter should fire if you open the app close to the beacon

### Actual behavior
regionDidEnter is not fired

**Comment by nbastoWM** [comment]
Doesn't anyone has this problem? 
If I switch off the beacon and then on, the regionDidEnter gets the beacon, but if I start the App with the beacon already on and close to the device, it does not detect the regionDidEnter.

**Comment by nbastoWM** [comment]
I did an workaround for this issue:
- start monitoring for regions
- wait 2 seconds
- startUpdatingLocation
- wait 4 seconds
- initializeBeacons + addListener

With this waiting times the device can find the beacon even if its already inside the region when it starts.
