### ISSUE TITLE
does setHardwareEqualityEnforced work ?

### ISSUE THREAD

**Issue by JayricMok** [MacKentoch/react-native-beacons-manager#134]
### Version
1.0.7

### Platform
Android

### OS version

android 7.0

I bought few iBeacon online and tried your example, yes it detect all the beacons. However, all the beacon have same uuid, this is sad until I saw there is a function call `setHardwareEqualityEnforced`, so I use this method `Beacons.setHardwareEqualityEnforced(true);` before or after `Beacons.detectIBeacons();` , but it not showing any mac address in `beaconsDidRange`  console

**Comment by sjaidka224** [comment]
Is is working on iOS as well ?

**Comment by JayricMok** [comment]
my application so far only target on Android, so I didn't try on iOS.
I use npm to install and it auto give me the version I using now

**Comment by JayricMok** [comment]
OK, i found a solution to get the mac address without `setHardwareEqualityEnforced(true)`

1. go node_modules\react-native-beacons-manager\android\src\main\java\com\mackentoch\beaconsandroid\BeaconsAndroidModule.java
2. find `createRangingResponse`
3. add `b.putString("address", beacon.getBluetoothAddress());` if you want address, or `b.putString("name", beacon.getBluetoothName());` if you want name

rebuild application, now received address and name
