### ISSUE TITLE
Beacons list is always empty while using iOS and Android as Beacons

### ISSUE THREAD

**Issue by jo2010** [MacKentoch/react-native-beacons-manager#14]
### Version
1.0.2

### Platform
iOS | Android

### OS version

iOS 10| android 6.0.

### Steps to reproduce

I don't have real beacons. I don't have two iOS devices. I have one android device and one iOS device. I tried with the sample code below. The event beaconsDidRange fires but beacons list is empty and the identifier is always Region1 in android and Estimotes in iOS. I tried using the same identifier for android and ios but still beacons list is empty. Events regionDidEnter and regionDidExit never fired. 

### Expected behavior
Detect android device as a beacon in iOS device.
Detect iOS device as a beacon in android device.
### Actual behavior
Beacons list is always empty

 ```
 if (Platform.OS === 'ios') {
      const region = {
          identifier: 'Estimotes',
          uuid: 'B9407F30-F5F8-466E-AFF9-25556B57FE6D'
      };
      Beacons.requestAlwaysAuthorization();
      Beacons.startMonitoringForRegion(region);
      Beacons.startRangingBeaconsInRegion(region);
      Beacons.startUpdatingLocation();
    } else {
        Beacons.detectIBeacons();
        try {
          Beacons.startMonitoringForRegion("Region1");
          Beacons.startRangingBeaconsInRegion("Region1");
        } catch (err) {
          console.log(`Beacons ranging not started, error: ${error}`)
        }
    }

    DeviceEventEmitter.addListener('beaconsDidRange', (data) => {
      console.log('Found beacons!', data);
    });
    DeviceEventEmitter.addListener('regionDidEnter', (data) => {
      console.log('regionDidEnter', data);
    });
    DeviceEventEmitter.addListener('regionDidExit', (data) => {
      console.log('regionDidExit', data);
    });
```

**Comment by MacKentoch** [comment]
Hi @jo2010 

I'm writing a more complete documentation to help with ranging and monitoring.

As you `monitor` beacons you need to call `requestAlwaysAuthorization()` since `requestWhenInUseAuthorization()` is not enough.

You already did it.

But in that case you have to add in your info.plist: `Privacy - Location Always Usage Description` (see [Beacons.requestAlwaysAuthorization()](https://github.com/MacKentoch/react-native-beacons-manager/blob/master/examples/samples/ranging.ios.md#1b-beaconsrequestalwaysauthorization-background-use-case)).

Concerning monitoring, I fixed:

- android in `v1.0.2`
- iOS in master branch (`npm install --save https://github.com/MacKentoch/react-native-beacons-manager.git` coming soon as v1.0.3)

**Comment by MacKentoch** [comment]
Another detail `android` specific, ensure to activate `location service` in pair with `bluetooth` on android 6.

On android 7, things are more simple: just activate `bluetooth`.

**Comment by jo2010** [comment]
@MacKentoch Added Privacy - Location Always Usage Description to info.list, both the location and bluetooth is enabled on android.  I just tried using npm install --save https://github.com/MacKentoch/react-native-beacons-manager.git also (Earlier I was using v1.0.2, not v1.0.1.), but nothing helps. Beacons list is empty. I also tried using two android devices android 5 and android 6, but on both the devices when I debug I see the beacons list is empty. 

Let know whether my understanding below is correct.  When the same app using the above sample is installed on both android device and iOS device, on android I'll see beacons list contains one beacon and that beacon identifier will be "Estimotes", and on iOS I'll see beacons list contains one beacon and that beacon identifier will be "Region1". Is that correct?

**Comment by jo2010** [comment]
Attached screenshots of what I see in the debug.

![screen shot 2017-03-19 at 11 40 58 pm](https://cloud.githubusercontent.com/assets/20960548/24090512/228bc8e0-0cfe-11e7-9be3-5e8a08250729.png)
![screen shot 2017-03-19 at 11 44 30 pm](https://cloud.githubusercontent.com/assets/20960548/24090514/28b1e0ec-0cfe-11e7-8515-6cc71638c28d.png)

**Comment by MacKentoch** [comment]
You have a really nice understanding.

In fact I've never seen that strange behaviour.
So it is interesting to study it then fix it (*thank you for this issue it will be helpful*).

Now lets break into small piece this issue to solve it.

First could you try to just range for beacons and comment startMonitoring:

```javascript
     Beacons.requestAlwaysAuthorization();
     // Beacons.startMonitoringForRegion(region);
     Beacons.startRangingBeaconsInRegion(region);
     Beacons.startUpdatingLocation();
```

By the way how do you test for example android as a beacon emitter?
I personally use [beacon simulator](https://play.google.com/store/apps/details?id=net.alea.beaconsimulator&hl=fr) (*it is complete: choose any kind of beacons, change the power etc...*).

**Comment by jo2010** [comment]
@MacKentoch Okay, I commented startMonitoringForRegion for both iOS code and android code. I see the same results. Beacons list is empty. So far, I have not used any beacon simulator as I thought if I install the same app in two devices and I can use them as beacon simulator and detector (is that correct?). Just now I tried using [beacon simulator ](https://play.google.com/store/apps/details?id=net.alea.beaconsimulator&hl=fr) that you mentioned and added a beacon and started broadcasting from android device. On my iOS app, below line prints only empty list of beacons with identifier as 'Estimotes'. Please note, I'm not running BeaconsDemo in react-native-beacons-manager, I'm running my app which has the above code. Maybe I made mistakes?

```
 DeviceEventEmitter.addListener('beaconsDidRange', (data) => {
     console.log('Found beacons!', data);
   });
```

**Comment by jo2010** [comment]
@MacKentoch Now, my app installed in android is able to detect the beacons coming from [beacon simulator ](https://play.google.com/store/apps/details?id=net.alea.beaconsimulator&hl=fr) installed on another android device and also the beacon coming from [beacon simulator](https://itunes.apple.com/us/app/beacon-simulator/id1098267039?mt=8) installed in my iPad.  But still my app running on different devices are not detecting each others as beacons. Why is that? 

When which line of executed on my app, its starts broadcasting as beacons? I beleive for iOS it's the below lines 
```
Beacons.startRangingBeaconsInRegion(region);
     Beacons.startUpdatingLocation();
```
and for android the below line
`
` Beacons.startRangingBeaconsInRegion("Region1");``

Correct?

**Comment by MacKentoch** [comment]
@jo2010 Wait *I think* there is a misunderstanding:

**This library does not provide anything to make your app as a beacon emitter.**

```javascript
Beacons.startUpdatingLocation(); // is required for monitoring to get the initial position of the device ≠ does not behave as an emitter
```

Am I wrong in what you want to do?

**Comment by jo2010** [comment]
@MacKentoch  Oh! Opps! Sorry for my wrong understanding. There is no issue then.

**Comment by sankar9659** [comment]
I faced this error while running in simulator. In real device, the screen shows as blank white screen.

**Comment by RashVenkat6795** [comment]
i am facing similar issue, i am implement the beacon transmission on both android and ios devices and when trying to monitor and range with help of this package, my android device is not listed in iphone and also vice versa.

@MacKentoch any thoughts on this ?
