### ISSUE TITLE
[Android] "App is running" permanent notification

### ISSUE THREAD

**Issue by iamandiradu** [MacKentoch/react-native-beacons-manager#144]
### Version
I'm using @newoceaninfosys' fork: github.com/newoceaninfosys/react-native-beacons-manager/

### Platform
Android

### OS version

Android 9.0

### Expected behavior
App opens (stealth) in background when beacon is detected.

### Actual behavior
There is a permanent notification warning me that the app is running.
![image](https://user-images.githubusercontent.com/24257156/61862496-aa9a8b00-aed6-11e9-97be-b24de5245c97.png)

**Comment by MacKentoch** [comment]
Please open an issue in the fork version.

**Comment by iamandiradu** [comment]
I would if I could, but the option is not available. :(
