### ISSUE TITLE
Info - Port React Native 60.0

### ISSUE THREAD

**Issue by brunoda6** [MacKentoch/react-native-beacons-manager#149]
Hi,
I would like to know if in a near future will be a port for RN 0.60?,

I've tried installing the package on RN 0.60 but failed so i used the RN 0.59.5 and there it works well,

Thanks,

**Comment by rnnyrk** [comment]
Did you figure it out?

**Comment by ptsteadman** [comment]
For autolink support you can use the newer, github version of beacons-manager (work in progress v1.1.0) instead of the [latest npm version (v1.0.7 released two years ago)](https://www.npmjs.com/package/react-native-beacons-manager) because the newer version has autolink support via a podspec file. If you do this, you might also need to remove the library from 'Frameworks, Libraries, and Embedded Content' in xcode.

ex in your package.json:

``
    "react-native-beacons-manager": "git://github.com/MacKentoch/react-native-beacons-manager.git#53c1bda",
```

**Comment by sankar9659** [comment]
**@ptsteadman** Will it work in react native 0.61.5 in ios also?

**Comment by imkazebui** [comment]
> **@ptsteadman** Will it work in react native 0.61.5 in ios also?

Try: 
react-native: 0.59.9
"react-native-beacons-manager": "git://github.com/MacKentoch/react-native-beacons-manager.git#53c1bda",

**Comment by pranavbadami** [comment]
> For autolink support you can use the version of beacons-manager on GitHub (work in progress v1.1.0) instead of the [latest npm version (v1.0.7 released two years ago)](https://www.npmjs.com/package/react-native-beacons-manager) because the newer version has autolink support via a podspec file. If you do this, you might also need to remove the library from 'Frameworks, Libraries, and Embedded Content' in xcode.
> 
> ex: change your package.json, run `npm install`, then `pod install`:
> 
> ```
>     "react-native-beacons-manager": "git://github.com/MacKentoch/react-native-beacons-manager.git#53c1bda",
> ```

Thanks for the help with this! Quick note, to get to this to work, I had to also first `npx react-native unlink react-native-beacons-manager` and then `npx react-native link react-native-beacons-manager`

**Comment by mozart27** [comment]
I was able to get this working by doing the following:

1. change the package.json to use the above mentioned github repo:
```
    "react-native-beacons-manager": "git://github.com/MacKentoch/react-native-beacons-manager.git#53c1bda",
```
2. I'm using React Native v0.61.4.  As such, there appears to be an issue for react-native-beacons-manager in this version where it brings in a dependency to an old version of react-native.  I had to modify `node_modules/react-native-beacons-manager/android/build.gradle`.  Here's the script i added as a package.json postinstall step
```
#!/bin/bash
#
# This script is used to fix the version number problem that prevents
# the react-native-beacons-manager from working properly.
#
#     node_modules/react-native-beacons-manager/android/build.gradle
#     -> change to dependencies { ... compile 'com.facebook.react:react-native:0.61.+' }

echo 'patching beacons manager package with correct react native version'
sed -i.bak 's/com\.facebook\.react:react-native:0\.20\.\+/com\.facebook\.react:react-native:0\.61\.\+/g' node_modules/react-native-beacons-manager/android/build.gradle

```
3. run `npm install` and then `pod install`
4. here's the code I'm using to enable the iBeacon ranging:
```

const turnOniOsBeaconScan = async () => {
  try {
    Beacons.requestWhenInUseAuthorization()

    const region1 = {
      identifier: 'region1',
      uuid: '<device1_uuid>'
    }

    Beacons.startRangingBeaconsInRegion(region1)

    const region2 = {
      identifier: 'region2',
      uuid: '<device2_uuid>'
    }

    Beacons.startRangingBeaconsInRegion(region2)

    Log.info('iOS Beacon Scan Enabled')
  } catch (err) {
    Log.warn(`error enabling iOS beacon scan: ${err}`)
  }
}
```

**Comment by cristinaITdeveloper** [comment]
> 3\. here's the code I'm using to enable the iBeacon ranging:



> I was able to get this working by doing the following:
> 
> 1. change the `package.json` to use the above mentioned github repo:
> 
> ```
>     "react-native-beacons-manager": "git://github.com/MacKentoch/react-native-beacons-manager.git#53c1bda",
> ```
> 
> 1. I'm using React Native v0.61.4.  As such, there appears to be an issue for react-native-beacons-manager in this version where it brings in a dependency to an old version of react-native.  I had to modify `node_modules/react-native-beacons-manager/android/build.gradle`.  Here's the script I added (called `postInstallFix.sh`) as a `postinstall` step in the `package.json` :
> 
> ```
> #!/bin/bash
> #
> # This script is used to fix the version number problem that prevents
> # the react-native-beacons-manager from working properly.
> #
> #     node_modules/react-native-beacons-manager/android/build.gradle
> #     -> change to dependencies { ... compile 'com.facebook.react:react-native:0.61.+' }
> 
> echo 'patching beacons manager package with correct react native version'
> sed -i.bak 's/com\.facebook\.react:react-native:0\.20\.\+/com\.facebook\.react:react-native:0\.61\.\+/g' node_modules/react-native-beacons-manager/android/build.gradle
> ```
> 
> then add this as the `postinstall` script line in the `package.json`:
> 
> ```
>   "scripts": {
>       ...
>       "postinstall": "./postInstallFix.sh",
>       ...
>   }
> ```
> 
> 1. run `npm install`
> 2. update pods by `cd ./ios` and run `pod install`
> 3. here's the code I'm using to enable the iBeacon ranging:
> 
> ```
> const turnOniOsBeaconScan = async () => {
>   try {
>     Beacons.requestWhenInUseAuthorization()
> 
>     const region1 = {
>       identifier: 'region1',
>       uuid: '<device1_uuid>'
>     }
> 
>     Beacons.startRangingBeaconsInRegion(region1)
> 
>     const region2 = {
>       identifier: 'region2',
>       uuid: '<device2_uuid>'
>     }
> 
>     Beacons.startRangingBeaconsInRegion(region2)
> 
>     Log.info('iOS Beacon Scan Enabled')
>   } catch (err) {
>     Log.warn(`error enabling iOS beacon scan: ${err}`)
>   }
> }
> ```

I have this error
`./postInstallFix.sh: Permission denied`

**Comment by brunoda6** [comment]
> Did you figure it out?

Hi,
what i did was the following:

-     run npm i
-     change the file (node_modules\react-native-beacons-manager\android\build.gradle) on this part:

`    dependencies {
        ...
        implementation 'com.facebook.react:react-native:0.61.+'
        ...
    }`
