### ISSUE TITLE
(Android)Beacons startRangingBeaconsInRegion not working on react native 0.61.1

### ISSUE THREAD

**Issue by srib1997** [MacKentoch/react-native-beacons-manager#154]
### Version
1.0.7

### Platform
Android

### OS version

android 9.0,android 7 and android 6

### Steps to reproduce
1.  Dont update react native to 0.61.1

### Actual behavior
When I call Beacons.startRangingBeaconsInRegion('REGION1') function, app will quit unexpectedly .

Downgrade react native 0.60.5 work but 0.61.1 not working

**Comment by arthurxu1979** [comment]
I met also met this issue recently. From the crash log, reactnative has changed putArray method in WritableMap class arround version 0.61 but code here is not changed. Thus current we could only live with lower version.

**Comment by samchan1995** [comment]
For others facing the same issue, it seems that the PR #155 is able to fix it.

**Comment by chentianci123** [comment]
> 我遇到的最近也遇到了这个问题。从崩溃日志中，反应式已更改WritableMap类arround版本0.61中的putArray方法，但此处的代码未更改。因此，当前我们只能使用较低版本。

你可以更改react-native-beacons-manager源码中的react-native版本，让其版本和项目中的版本一致

**Comment by daeki88** [comment]
Thanks to @chentianci123 ,
I solved the problem by changing the version number in the "node_modules\react-native-beacons-manager\android\build.gradle" file.
Change the react-native version in dependencies to my project react-native version number(0.61.2) as below
```
dependencies {
    ...
    implementation 'com.facebook.react:react-native:0.61.+'
    ...
}
```

**Comment by CarstenHoyer** [comment]
I think this is the issue: https://github.com/facebook/react-native/issues/27088#issuecomment-552414457

**Comment by mslevin** [comment]
@daeki88 This worked for me, much appreciated.

**Comment by RM-Eric** [comment]
@daeki88 That fixed it for me too, thanks!

**Comment by sankar9659** [comment]
@srib1997  can you send your code? beacons are detecting?

**Comment by hadpro24** [comment]
> Thanks to @samchan1995 and @chentianci123 ,
> I solved the problem by changing the version number in the `node_modules\react-native-beacons-manager\android\build.gradle` file.
> I changed the react-native version in dependencies part to my project's react-native version number(0.61.2) or (`react-native:+`) as below
> 
> ```
> dependencies {
>     ...
>     implementation 'com.facebook.react:react-native:0.61.+'
>     ...
> }
> ```
> 
> Thanks!

It's work for me.

**Comment by ankitsdglobal** [comment]
> Thanks to @samchan1995 and @chentianci123 ,
> I solved the problem by changing the version number in the `node_modules\react-native-beacons-manager\android\build.gradle` file.
> I changed the react-native version in dependencies part to my project's react-native version number(0.61.2) or (`react-native:+`) as below
> 
> ```
> dependencies {
>     ...
>     implementation 'com.facebook.react:react-native:0.61.+'
>     ...
> }
> ```
> 
> Thanks!

In android it is working now but ios still giving issue

**Comment by MagaliCF** [comment]
For me works in `node_modules\react-native-beacons-manager\android\build.gradle` file

`dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.facebook.react:react-native:+'
    implementation 'org.altbeacon:android-beacon-library:2.9.2'
}
`
