### ISSUE TITLE
Question: When to use startMonitoringForRegion and when to use startRangingBeaconsInRegion?

### ISSUE THREAD

**Issue by jo2010** [MacKentoch/react-native-beacons-manager#16]
Is using startRangingBeaconsInRegion consume more battery than startMonitoringForRegion?

**Comment by r-bansal** [comment]
`startRangingBeaconsInRegion` - will happen more frequency (think each scan cycle, so every 1s), and is normally when the user is using the app (app is active, in foreground). It only works when the app is active.

`startMonitoringForRegion` - will happen on region enter/exit, so consumes less battery, and is normally to alert the user to open the app (they are close by something).

monitoring events are not as frequent as ranging - so ranging consumes more.
