### ISSUE TITLE
Listening beacons in background doesn't work after 1 minute

### ISSUE THREAD

**Issue by Kranysys** [MacKentoch/react-native-beacons-manager#167]
### Version
1.0.1

### Platform
Android

### OS version
Android 9.0

### Expected behavior
Listening the beacons after one minute when the app is in background.

### Actual behavior
When the application is in background, it works perfect before 1 minute, then, the library doesn't detect any beacons.
The listener still working like there is no beacon detected.

![image](https://user-images.githubusercontent.com/33665069/69345578-9f335280-0c71-11ea-987c-e3ca4f394081.png)

**Comment by GiacomoMasi** [comment]
Which version of react native are you using?

**Comment by Kranysys** [comment]
> Which version of react native are you using?

Tested with 0.59.9 and 0.60.4 on different projects, same result.

**Comment by GiacomoMasi** [comment]
Can you upload the code?

Because I'm using 0.61.4 or 0.60.4 version of RN, and when I call the function **startRangingBeaconsInRegion**  the application  closes its self. May be since the version 0.60 something doesn't work in the right way. In the version 0.59 works for me.

**Comment by Kranysys** [comment]
Using the example on this repository:

    Beacons.detectIBeacons();

    // Start detecting all iBeacons in the nearby
    try {
      await Beacons.startRangingBeaconsInRegion('REGION1')
      console.log(`Beacons ranging started succesfully!`)
    } catch (err) {
      console.log(`Beacons ranging not started, error: ${error}`)
    }

    // Print a log of the detected iBeacons (1 per second)
    subscription = DeviceEventEmitter.addListener('beaconsDidRange', (data) => {
      console.log('Found beacons!', data.beacons)
    })

I have the same result with Monitoring a specific beacon UID also.

**Comment by GiacomoMasi** [comment]
I tested your code and it works well.
I see in my tests that in RN 0.61.4 the application crashes after the calls of the  **startRangingBeaconsInRegion** function. May be the duration of the scanner depends on the model of the phone

**Comment by Kranysys** [comment]
Issue founded, this problem is due to battery saver present on many devices, more informations:
https://dontkillmyapp.com/xiaomi
It works when we disable "Saving Power in The Background".

**Comment by sankar9659** [comment]
It's working for me in android but not work in IOS, my react native version is 0.61.5

**Comment by Srikanth-Enuguru** [comment]
@Kranysys @sankar9659 @GiacomoMasi  Are you able to scan the iBeacons using this library?
If yes could you please share your code or help me in fixing [this issue](https://github.com/MacKentoch/react-native-beacons-manager/issues/266).

**Comment by GiacomoMasi** [comment]
Hi,
I did a project using this library (I think in 2017). I don't know how this
library changes nowadays.
I suggest you follow the code of the docs page and try to work with a
simple example, and then add new features.

Giacomo

Il giorno gio 27 lug 2023 alle ore 06:57 Srikanth Enuguru <
***@***.***> ha scritto:

**Comment by akankshaingle** [comment]
I turned off Power Saving mode and now my Android can detect beacons in the background too.
