### ISSUE TITLE
I need to continue monitoring the beacon after exiting the app, what should I do

### ISSUE THREAD

**Issue by chentianci123** [MacKentoch/react-native-beacons-manager#168]
### Version
1.0.7

### Platform
 Android

### OS version

android 6.0...

**Comment by Srikanth-Enuguru** [comment]
@chentianci123 Are you able to scan the iBeacons using this library?
If yes could you please share your code or help me in fixing [this issue](https://github.com/MacKentoch/react-native-beacons-manager/issues/266).
