### ISSUE TITLE
Incompatible with android version, resulting in no beacon detection

### ISSUE THREAD

**Issue by chentianci123** [MacKentoch/react-native-beacons-manager#169]
### Version
1.0.7

android Version:
ok: 7.1.1
error: 10.0

**Comment by chentianci123** [comment]
question:  beacons is [ ]

**Comment by chentianci123** [comment]
My problem is solved, mate30 android10 needs to turn on GPS

**Comment by Srikanth-Enuguru** [comment]
@chentianci123  Are you able to scan the iBeacons using this library?
If yes could you please share your code or help me in fixing [this issue](https://github.com/MacKentoch/react-native-beacons-manager/issues/266).
