### ISSUE TITLE
Android X support required for React Native >= 0.60.0

### ISSUE THREAD

**Issue by Saumyadip-Pramanik** [MacKentoch/react-native-beacons-manager#171]
### Version
1.0.7

### Platform
Android

> Task :react-native-beacons-manager:compileReleaseJavaWithJavac FAILED
/Users/..../node_modules/react-native-beacons-manager/android/src/main/java/com/mackentoch/beaconsandroid/BeaconsAndroidModule.java:7: error: package android.support.annotation does not exis
import android.support.annotation.Nullable;
                                 ^

/Users/..../node_modules/react-native-beacons-manager/android/src/main/java/com/mackentoch/beaconsandroid/BeaconsAndroidModule.java:331: error: cannot find symbol
    private void sendEvent(ReactContext reactContext, String eventName, @Nullable WritableMap params) {
                                                                         ^
  symbol:   class Nullable
  location: class BeaconsAndroidModule

**Comment by chentianci123** [comment]
You try version 1.0.7

**Comment by Saumyadip-Pramanik** [comment]
@chentianci123 I have tried that, still not working.

**Comment by Saumyadip-Pramanik** [comment]
@MacKentoch Please provide an update for androidx / RN 0.60.0+

**Comment by Saumyadip-Pramanik** [comment]
Also after running 'npx jetify', the above error gets resolved but following error occurs:

> Task :react-native-beacons-manager:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-beacons-manager:verifyReleaseResources'.

**Comment by tomdaniel0x01** [comment]
> Also after running 'npx jetify', the above error gets resolved but following error occurs:
> 
> > Task :react-native-beacons-manager:verifyReleaseResources FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':react-native-beacons-manager:verifyReleaseResources'.

[](https://github.com/MacKentoch/react-native-beacons-manager/pull/155/files) seems to have fixed it for me.

**Comment by tomdaniel0x01** [comment]
> Also after running 'npx jetify', the above error gets resolved but following error occurs:
> 
> > Task :react-native-beacons-manager:verifyReleaseResources FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':react-native-beacons-manager:verifyReleaseResources'.

I just fixed this issue by replacing the v1.0.7 `android/build.gradle` with the [latest version](https://github.com/MacKentoch/react-native-beacons-manager/blob/master/android/build.gradle) in this repo.

**Comment by organom** [comment]
Current master version is using  org.jetbrains.annotations.Nullable instead of the android.support.annotation.Nullable.

Add    ` implementation 'com.intellij:annotations:+@jar' `  to the android/build.gradle dependencies.
In case of the android.support.annotation.Nullable  add  ` implementation 'com.android.support:support-annotations:28.0.0' ` instead.

Will add a pull request later on to the current master to allow it to build for Android
