### ISSUE TITLE
Not working in IOS, getting "Null is not an object in Beacons.requestWhenInUseAuthorization();"

### ISSUE THREAD

**Issue by sankar9659** [MacKentoch/react-native-beacons-manager#179]
**Version**
package: 1.0.7
react: 16.9.0
react-native : 0.61.5

**Platform**
iOS

**OS version**
iOS 13

**Steps to reproduce**
1.npm react-native-beacons-manager
2.react-native link react-native-beacons-manager
3. pod install
...others steps on iOS to background mode...
Expected behavior
Works

Actual behavior
iOS gives me the error:

In pod install: 'No podspeec found in this path"
Xcode error: 'React/RCTBridge.h' file not found,
In simulator getting this error: 'Null is not an object in Beacons.requestWhenInUseAuthorization();"

"react": "16.9.0",
"react-native": "0.61.5",
"react-native-beacons-manager": "^1.0.7"

Someone can help me?

my code is here:

import React from 'react';
import {
	Dimensions,
	ImageBackground,
	TouchableOpacity,
	View,
	StatusBar,
	Platform,
	Alert,
	DeviceEventEmitter
} from 'react-native';
import Pulse from 'react-native-pulse';
import _map from 'lodash/map';
import Reactotron from 'reactotron-react-native';
import ScalableText from 'react-native-text';
import { connect } from 'react-redux';
import RNModal from 'react-native-modal';
import { NavigationEvents } from 'react-navigation';
import Icon from 'react-native-vector-icons/Ionicons';
import _filter from 'lodash/filter';
import _intersectionBy from 'lodash/intersectionBy';
import _forEach from 'lodash/forEach';
import Beacons from 'react-native-beacons-manager';

class PulseScreen extends React.Component {

	startBeacon = () => {
		if (Platform.OS === 'ios') {
			Reactotron.log('iosPLatform');
			const region = {
				identifier: 'estimote',
				uuid: '1a9f0cfb7d4bfc0e3071bffe2455261e'
			};
			Beacons.requestAlwaysAuthorization();
			Beacons.startRangingBeaconsInRegion(region)
				.then((data) => {
					Alert.alert('', `Beacons monitoring started!`);
				})
				.catch((error) => {
					Alert.alert('', `Beacons start error! IOS`);
				});
			DeviceEventEmitter.addListener('beaconsDidRange', (data) => {
				Alert.alert('', 'beacons monitering started')
				if (data.beacons.length) {
					this.setState({ detectedBeacons: data.beacons });
					Alert.alert(`Found beacons!`, JSON.stringify(data.beacons));
				}
			});

			Beacons.startUpdatingLocation();
		}
		else {
			Reactotron.log('else');
			Beacons.detectIBeacons();
			Beacons.detectAltBeacons();
			Beacons.detectEstimotes();
			Beacons.detectEddystoneUID();
			Beacons.detectEddystoneTLM();
			Beacons.detectEddystoneURL();
			Beacons.startRangingBeaconsInRegion('REGION1')
				.then((data) => {
					Alert.alert('', `Beacons monitoring started!`);
				})
				.catch((error) => {
					Alert.alert('', `Beacons start error!`);
				});
			DeviceEventEmitter.addListener('beaconsDidRange', (data) => {
				if (data.beacons.length) {
					this.setState({ detectedBeacons: data.beacons });
					Alert.alert(`Found beacons!`, JSON.stringify(data.beacons));
				}
			});
		}
	};

	render() {
		const { nearbyStores } = this.state;
		const { beaconList } = this.props;

		return (
			<View>
				<NavigationEvents
					onWillFocus={() => {
						StatusBar.setBarStyle('light-content', true);
						if (beaconList.length) {
							this.startBeacon();
						}
					}}
					onWillBlur={() => {
						if (beaconList.length) {
							Beacons.stopRangingBeaconsInRegion('REGION1')
								.then(() => {
									Alert.alert('', `Beacons monitoring stopped succesfully!`);
								})
								.catch((error) => {
									Alert.alert(`Beacons stop error!`);
								});
						}
						StatusBar.setBarStyle('dark-content', true);
					}}
				/>

**Comment by sankar9659** [comment]
**@MacKentoch**  give me the solution, we have release on wednesday. Its working in android, but not working in IOS.

**Comment by sankar9659** [comment]
**@ptsteadman**  Please give me the solution. its not detecting beacons in ios. I have also tried with this version ("react-native-beacons-manager": "git://github.com/MacKentoch/react-native-beacons-manager.git#53c1bda",) but no luck.

**Comment by nbastoWM** [comment]
According to #153 there's yet no solution for ios after version 13.

**Comment by mozart27** [comment]
I was able to get this working by doing the following:

1. change the `package.json` to use the above mentioned github repo:
```
    "react-native-beacons-manager": "git://github.com/MacKentoch/react-native-beacons-manager.git#53c1bda",
```
2. I'm using React Native v0.61.4.  As such, there appears to be an issue for react-native-beacons-manager in this version where it brings in a dependency to an old version of react-native.  I had to modify `node_modules/react-native-beacons-manager/android/build.gradle`.  Here's the script I added (called `postInstallFix.sh`) as a `postinstall` step in the `package.json` :
```
#!/bin/bash
#
# This script is used to fix the version number problem that prevents
# the react-native-beacons-manager from working properly.
#
#     node_modules/react-native-beacons-manager/android/build.gradle
#     -> change to dependencies { ... compile 'com.facebook.react:react-native:0.61.+' }

echo 'patching beacons manager package with correct react native version'
sed -i.bak 's/com\.facebook\.react:react-native:0\.20\.\+/com\.facebook\.react:react-native:0\.61\.\+/g' node_modules/react-native-beacons-manager/android/build.gradle
```

then add this as the `postinstall` script line in the `package.json`:
```
  "scripts": {
      ...
      "postinstall": "./postInstallFix.sh",
      ...
  }
```

3. run `npm install`
4. update pods by `cd ./ios` and run `pod install`
5. here's the code I'm using to enable the iBeacon ranging:
```
const turnOniOsBeaconScan = async () => {
  try {
    Beacons.requestWhenInUseAuthorization()

    const region1 = {
      identifier: 'region1',
      uuid: '<device1_uuid>'
    }

    Beacons.startRangingBeaconsInRegion(region1)

    const region2 = {
      identifier: 'region2',
      uuid: '<device2_uuid>'
    }

    Beacons.startRangingBeaconsInRegion(region2)

    Log.info('iOS Beacon Scan Enabled')
  } catch (err) {
    Log.warn(`error enabling iOS beacon scan: ${err}`)
  }
}
```

**Comment by sankar9659** [comment]
> I was able to get this working by doing the following:
> 
> 1. change the `package.json` to use the above mentioned github repo:
> 
> ```
>     "react-native-beacons-manager": "git://github.com/MacKentoch/react-native-beacons-manager.git#53c1bda",
> ```
> 
> 1. I'm using React Native v0.61.4.  As such, there appears to be an issue for react-native-beacons-manager in this version where it brings in a dependency to an old version of react-native.  I had to modify `node_modules/react-native-beacons-manager/android/build.gradle`.  Here's the script I added (called `postInstallFix.sh`) as a `postinstall` step in the `package.json` :
> 
> ```
> #!/bin/bash
> #
> # This script is used to fix the version number problem that prevents
> # the react-native-beacons-manager from working properly.
> #
> #     node_modules/react-native-beacons-manager/android/build.gradle
> #     -> change to dependencies { ... compile 'com.facebook.react:react-native:0.61.+' }
> 
> echo 'patching beacons manager package with correct react native version'
> sed -i.bak 's/com\.facebook\.react:react-native:0\.20\.\+/com\.facebook\.react:react-native:0\.61\.\+/g' node_modules/react-native-beacons-manager/android/build.gradle
> ```
> 
> then add this as the `postinstall` script line in the `package.json`:
> 
> ```
>   "scripts": {
>       ...
>       "postinstall": "./postInstallFix.sh",
>       ...
>   }
> ```
> 
> 1. run `npm install`
> 2. update pods by `cd ./ios` and run `pod install`
> 3. here's the code I'm using to enable the iBeacon ranging:
> 
> ```
> const turnOniOsBeaconScan = async () => {
>   try {
>     Beacons.requestWhenInUseAuthorization()
> 
>     const region1 = {
>       identifier: 'region1',
>       uuid: '<device1_uuid>'
>     }
> 
>     Beacons.startRangingBeaconsInRegion(region1)
> 
>     const region2 = {
>       identifier: 'region2',
>       uuid: '<device2_uuid>'
>     }
> 
>     Beacons.startRangingBeaconsInRegion(region2)
> 
>     Log.info('iOS Beacon Scan Enabled')
>   } catch (err) {
>     Log.warn(`error enabling iOS beacon scan: ${err}`)
>   }
> }
> ```

A lot of Thanks its works

**Comment by kirantripathi** [comment]
I am also facing the same  issue in react-native 0.63.3. @sankar9659  @mozart27  do you guys have any idea on how to solve it.

**Comment by sankar9659** [comment]
@kirantripathi  try like this in package.json it working good.
 "react-native-beacons-manager": "git://github.com/MacKentoch/react-native-beacons-manager.git#53c1bda",
