### ISSUE TITLE
Adding multiple regions in iOS

### ISSUE THREAD

**Issue by r-bansal** [MacKentoch/react-native-beacons-manager#18]
### Version
1.0.1

### Platform
iOS

### OS version

iOS 10
### Steps to reproduce
1.  Add multiple regions
2. iOS not supported
3.  

### Expected behavior
Should add and detect multiple regions.

### Actual behavior
Does not work. This maybe related to the todo: startRangingBeaconsInRegion and startMonitoringForRegion should return promises like android

Just testing this out further to confirm, do share if you think of anything.

**Comment by MacKentoch** [comment]
I just tested ranging and it seems like it is fixed.

Just need to test monitoring, then both ranging and monitoring.

Note: I use [example](https://github.com/MacKentoch/react-native-beacons-manager/tree/master/examples/BeaconsDemo) as usual when I test something.

Note2: I created a [gitter channel for react-native-beacons-manager](https://gitter.im/react-native-beacons-manager/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link) (tag on README).
I find gitter pretty handy for chatting on a repository or anything that would not be an issue.

**Comment by MacKentoch** [comment]
I close this issue since issue is fixed.

I will add an example later for giving an idea on how to deal with multiple region on iOS.
