### ISSUE TITLE
Detect Beacon without uuid (IOS)

### ISSUE THREAD

**Issue by raphaelAdekz** [MacKentoch/react-native-beacons-manager#180]
### Version
1.0.1

### Platform
iOS | Android

### OS version

iOS 13| android 7.0...

Is there any way to detect the beacons in IOS without needing the iBeacon uuid? Because my application uses the uuid of the beacon found to make a query in the database, and on android if I pass NULL to uuid, it detects all, however on IOS this does not work

**Comment by adarshraj87** [comment]
@raphaelAdekz How did you tackle the issue?

**Comment by raphaelAdekz** [comment]
> @raphaelAdekz How did you tackle the issue?

I was using it wrong, in fact all beacons must have the same uuid and what should be used to differentiate them is the major and the minor

**Comment by Srikanth-Enuguru** [comment]
@raphaelAdekz @adarshraj87  Are you able to scan the iBeacons using this library?
If yes could you please share your code or help me in fixing [this issue](https://github.com/MacKentoch/react-native-beacons-manager/issues/266).
