### ISSUE TITLE
issue in example

### ISSUE THREAD

**Issue by ducduong** [MacKentoch/react-native-beacons-manager#2]
var {DeviceEventEmitter} = React;

shouldn't it be React native instead?

### Version
1.0.1

### Platform
iOS | Android

### OS version

iOS 10| android 7.0...

**Comment by MacKentoch** [comment]
Hi @ducduong 

If I'm not wrong you talk about example for iOS in README:
```javascript
var React = require('react-native');
var {DeviceEventEmitter} = React; // React is a variable = all React-Native
```

**You are right!**
> This way leads to confusion. Sorry about that.

I already fixed it (not pushed right now in github). 

It was an heritage that came because of a copy paste from previous repository.

**Comment by MacKentoch** [comment]
README is updated
