### ISSUE TITLE
Background Mode in Android

### ISSUE THREAD

**Issue by ElCapitanDre** [MacKentoch/react-native-beacons-manager#20]
### Version
1.0.1

### Platform
iOS | Android

### OS version

iOS 10| android 7.0...

Just wondering if you have a date for when the android background mode will be available?

**Comment by MacKentoch** [comment]
Hi @ElCapitanDre 

These days I was particularly busy.

Your title talks about android only.
You description may not be updated: iOS works for sure I validated few weeks ago.

**Comment by MacKentoch** [comment]
@ElCapitanDre 

Did you try on android 7+?

There no issue, when application is in background all work as in foreground.

**Comment by ElCapitanDre** [comment]
Hi @MacKentoch 
Thanks for the quick response.

I was asking only for android beacuse the BACKGROUNDS_MODE.md file already said that ios is working, yet the android version only said TOO ADD.

Thanks for the suggestion i will try it as soon as i can

**Comment by MacKentoch** [comment]
@ElCapitanDre Thank you for creating issue.

It **helps a lot** to detect and fix issues or missing features.

And I forgot to mention that I tested with master branch version (*it should be the same as fastest `v1.0.3`*) so feel free to give a feedback with the version you actually use.

**Comment by r-bansal** [comment]
@MacKentoch, @ElCapitanDre - Just a note that background mode works fine in Android and iOS. iOS even works with the app inactive, however, once the app is killed in Android - it will not work. I am looking for a solution for this as well.

**Comment by MacKentoch** [comment]
Thank you @r-bansal.

To make it work on android when app is killed, there is some native code to add like talked [here](https://github.com/MacKentoch/react-native-beacons-manager/issues/6#issuecomment-291350569).

I don't know the precise code right now, but at least it works and won't need something to add in the library.

**Comment by jo2010** [comment]
@r-bansal @MacKentoch  how come background mode works fine in Android and iOS? For me, Android is unable to detect iOS when iOS app runs in the background. Do you know what could be the problem?

**Comment by MacKentoch** [comment]
@jo2010 just ensure you ask for `Beacons.requestAlwaysAuthorization()` and not only when application in active to make it work in background.

**Comment by Pacn91** [comment]
@MacKentock could you make an example using background detection for Android and iOS? I really do not know what to do to search for beacons on background mode. I would be very grateful.

**Comment by MacKentoch** [comment]
@Pacn91 I am preparing an example in [BeaconsDemo](https://github.com/MacKentoch/react-native-beacons-manager/blob/master/examples/BeaconsDemo/index.ios.js).

One things among others I'm doing in the same time 😄

**Comment by Pacn91** [comment]
@MacKentoch Thank you so much! And I'm sorry to bother you :/

**Comment by Pacn91** [comment]
@MacKentoch the background detection only works with monitoring? I'm asking that because I'm working on an APP that shows and describes the monuments on my city, And the ideia is that when a user is passing by a monument he receives a notification. For what I've been reading, monitoring "works no matter whether the app is running, suspended, or killed" (https://community.estimote.com/hc/en-us/articles/203356607-What-are-region-Monitoring-and-Ranging). Your library works in the same way? Can detect beacons even if the app is killed? And Ranging really dont work with background mode?

Sorry about my horrible english xD
