### ISSUE TITLE
com.facebook.react.bridge errors during gradlew assembleRelease

### ISSUE THREAD

**Issue by damienleri** [MacKentoch/react-native-beacons-manager#22]
I'm able to use this library on an android device but when I try to package the APK I get this error. Any ideas?

```
android> ./gradlew assembleRelease
...
:react-native-beacons-manager:processReleaseJavaRes UP-TO-DATE
:react-native-beacons-manager:compileReleaseJavaWithJavac
/Users/damien/pennpass/node_modules/react-native-beacons-manager/android/src/main/java/com/mackentoch/beaconsandroid/BeaconsAndroidModule.java:10: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.Callback;
.. (more of these same errors about com.facebook.react.bridge)
```

**Comment by MacKentoch** [comment]
Hi @damienleri,

Thank you for this issues.

Could you give me more details on your versions like React Native and react-native-beacons-manager?

I need to investigate since like that I don't have an answer right now.

**Comment by damienleri** [comment]
Thanks for the quick response. But I did this and it's fixed now.

```
gradlew clean
rm -rf ~/.gradle/caches/*
``

**Comment by MacKentoch** [comment]
Nice job!

Thank you for sharing your fix.
