### ISSUE TITLE
Do you plan to support the Estimote Indoor Location?

### ISSUE THREAD

**Issue by angelstoone** [MacKentoch/react-native-beacons-manager#23]
Hi guys,

Do you plan to integrate the Estimote Indoor Location to this project even though is available just on iOS? Would you accept a PR about this feature?

Cheers

**Comment by MacKentoch** [comment]
Hi,

Yes it is planned.
But any PR is always welcome since very helpful

**Comment by MacKentoch** [comment]
linked to #3
