### ISSUE TITLE
android app crashing when startMonitoringForRegion is called

### ISSUE THREAD

**Issue by danielgay75** [MacKentoch/react-native-beacons-manager#24]
### Version
1.0.1

### Platform
Android

### OS version

android 7.0

### Steps to reproduce
1.  Beacons.detectIBeacons()
2. Beacons.startMonitoringForRegion({ identifier: 'my-region' }) 
3.  crash

### Expected behavior
should monitor all beacons in that region; according to docs uuid is optional

### Actual behavior
crash

**Comment by MacKentoch** [comment]
Sorry for delay, but does it occurs with v1.0.4?

**Comment by prancky** [comment]
@MacKentoch I'm having the same app crashing issue with V1.0.4.

**Comment by diegorodriguesvieira** [comment]
+1

**Comment by acowling** [comment]
I'm encountering this issue now after updating to RN 0.46.4 from RN 0.42. The version of RNBM (v1.0.4) hasn't changed during this update.
None of my logic for ranging for beacons has changed.
I'm not receiving any error messages other than the App stopping.

**Comment by andreassavva** [comment]
Crashes for me too. Apparently the `beaconsAndroid` variable in `module.android.js` is `undefined`.

**Comment by andreassavva** [comment]
Might have something to do with using CRNA and ejecting with ExpoKit afterwards. `NativeModules` returns an empty object for some reason.

**Comment by MacKentoch** [comment]
It should be related to #38.

It is fixed with v1.0.6.
