### ISSUE TITLE
 Could not find method compile() for arguments

### ISSUE THREAD

**Issue by SERCHAT** [MacKentoch/react-native-beacons-manager#244]
### Version
1.0.6

### Platform
iOS | Android

### OS version

iOS 10| android 7.0...

### Steps to reproduce
1.  get package with npm
2.  run comman "npm run android" on fresh react native project

### Expected behavior
What should happen
The code should be compile without errors

### Actual behavior
What is happening
the code does not compile. I use gradle version 7+ and openJDK 11 and react-native v.0.69
problem occurred evaluating project ':react-native-beacons-manager'.
> Could not find method compile() for arguments [org.altbeacon:android-beacon-library:2.16.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by sashko9807** [comment]
compile method() has been deprecated starting from gradle v7. Replace 'compile'  with 'implementation'
For reference
https://github.com/sashko9807/react-native-beacons-manager/commit/32d013ebff87733cccf60f62532cf509f540daf0

**Comment by Srikanth-Enuguru** [comment]
@SERCHAT @sashko9807 Are you able to scan the iBeacons using this library?
If yes could you please share your code or help me in fixing [this issue](https://github.com/MacKentoch/react-native-beacons-manager/issues/266).
