### ISSUE TITLE
Receive empty for major and minor in case on Monitoring

### ISSUE THREAD

**Issue by farminf** [MacKentoch/react-native-beacons-manager#25]
### Version
1.0.4

### Platform
Android

### OS version

android 7.0...

### Steps to reproduce
1.  
2.  
3.  

### Expected behavior
It monitors the UUID and onEnter or onExit event it get the ibeacon with that UUID and major and minor number

### Actual behavior
Monitoring base on the UUID , it listens onEnter and get the beacon but always major and minor are empty and it shows 0

**Comment by farminf** [comment]
Ok After some debugging and reading on Internet I found that monitoring region just return the major or minor (or both) that has been configured.

**Comment by MacKentoch** [comment]
Glad you found an answer.

Yes first time I remember I struggled a bit because I thought I had a 🐛

**Comment by farminf** [comment]
Yes :) but in general, I'm sad that it has 20 regions limitation because I can't monitor just based on the UUID and get the minor major so I need to configure every region with UUID, minor and major and understand where I am.

**Comment by niv-breez** [comment]
What if I have more than 1000 beacons ? how to deal with this ?
