### ISSUE TITLE
Callback requestAlwaysAuthorization

### ISSUE THREAD

**Issue by Clowning** [MacKentoch/react-native-beacons-manager#26]
Hey ! Thanks for your wrapper :-) ! 

I need to know if use allow or decline the pop when he needs to select if he is agree to authorize app to use bluetooth ! How can you do this  ?

Thanks :-)

**Comment by MacKentoch** [comment]
Hi @Clowning 

If user declines when popup shows up, iOS won't allow the library / the application to use what user declined = bluetooth won't work.

It is up to the dev to check if user authorised or not (by checking bluetooth access available for instance).

In fact it is iOS generic way of managing permissions (*beyond this library scope*).
