### ISSUE TITLE
Ranging while using bluetooth peripherals

### ISSUE THREAD

**Issue by piuholo** [MacKentoch/react-native-beacons-manager#31]
Noticed this problem while testing ranging for beacons on **iPhone 6s**.
When I have my AirPods connected to the phone and data is being transferred between the device and the headphones via BT, the ranging for iBeacons with this library gets very spotty.
It can still detect the beacons here and there, but the signal strength often reports as 0 and accuracy as -1.

This might be the case while using other Bt peripherals too. I'm wondering if this is a problem with the library or a problem with iOS / the device itself. Can someone reproduce the problem?

### Version
1.0.4

### Platform
iOS

### OS version

iOS 10.3.2

### Steps to reproduce
1.  Use bluetooth headphones (Apple AirPods in my case)
2.  startMonitoringForRegion
3.  log rssi / accuracy

### Expected behavior
Should detect beacons normally.

### Actual behavior
Ranging does detect beacons, but the detection is very spotty and RSSI is often reported as "0" and accuracy as "-1".

**Comment by piuholo** [comment]
Seems like it could be affecting iOS in general, according to Apple Dev forums. See:

https://forums.developer.apple.com/message/205532#205532

https://forums.developer.apple.com/message/181866#181866

**Comment by MacKentoch** [comment]
@piuholo it must be device related as you mentioned.

I don't have AirPods so testing with them should be complicated.

But it should work the same for them as bluetooth devices.

**Comment by MacKentoch** [comment]
Close it since seems like more related to device than to react-native-beacons-manager
