### ISSUE TITLE
Conflict with geolocation library that causes app to crash

### ISSUE THREAD

**Issue by plbrault** [MacKentoch/react-native-beacons-manager#34]
### Version
1.0.4

### Platform
iOS

### OS version

iOS 10

### Steps to reproduce
1. Create a React Native app that integrates both `react-native-beacons-manager` and `react-native-background-geolocation` libraries
2. Add code to monitor beacons using `react-native-beacons-manager`
3. Add code to monitor a geofence around current location using `react-native-background-geolocation`
4. Run the app
5. Exit monitored geofence

### Expected behavior
The region exit triggered by `react-native-background-geolocation` should have no effect on `react-native-beacons-manager`.

### Actual behavior
When `react-native-background-geolocation` triggers a region exit, it triggers `locationManager:didExitRegion` in `react-native-beacons-manager`. Since the region passed to the function is not a beacon region, the `proximityUUID` selector does not exist, and an error is thrown:

```
Fatal Exception: NSInvalidArgumentException
-[CLCircularRegion proximityUUID]: unrecognized selector sent to instance 0x170007230
```

A similar issue is documented with a solution on the `react-native-ibeacon` package:
https://github.com/frostney/react-native-ibeacon/issues/35

**Comment by MacKentoch** [comment]
Alright if someone can PR a solution.

Already busy in merging interesting and huge PRs right now

**Comment by plbrault** [comment]
I will submit a PR later this month.

**Comment by jdegger** [comment]
How do we go about fixing this issue? We are encountering this with react-native-background-geolocation. 

We are getting a `NSInvalidArgumentException-[RNiBeacon locationManager:didExitRegion:]`
