### ISSUE TITLE
Expo client: undefined is not an object

### ISSUE THREAD

**Issue by haaslukas** [MacKentoch/react-native-beacons-manager#35]
### Version
1.0.4

### Platform
Windows10 (PowerShell)

### OS version
Android 6.0.1

### Steps to reproduce
I started with a fresh installation on Windows 10 and followed the medium article. I used the following node, npm and react native versions:
node: 6.11.1
npm: 3.10.10
react-native-cli: 2.0.1
react-native: 0.45.1
Since I wanted to try the Expo client, I didn't git clone https://github.com/MacKentoch/reactNativeBeaconExample.git but just copied the beaconRangingOnly code into my App.js and changed the export default class name
`export default class RNbeaconArticle extends React.Component {
...`
I also registered the projects dependencies.

### Actual behavior
npm start builds everything fine, but on my Android phone I get the following error:
`undefined is not an object (evaluationg 'beaconsAndroid.addParser')`
Could it be that the react-native-beacons-manager won't work with Expo?

**Comment by utsav-dholakia** [comment]
I'm having the same issue, although my node and npm versions are different(I don't think it matters anyway with the issue). While debugging it seems that somehow the component "BeaconsAndroidModule" which should have been registered with NativeModules is not happening which is causing it to be undefined. It would be helpful if someone can help with the issue.

**Comment by ddresch** [comment]
Did the whole setup process with plain `react-native init` which is working normally. 

Found this page about Expo and native code linking: 
https://docs.expo.io/versions/v17.0.0/guides/expokit.html

> What does using ExpoKit mean for a CRNA user?
> 
> If you want to add custom native code to your Expo app, you will need to use ExpoKit. With CRNA, you have two options: you can either eject to a normal React Native project, without any dependencies on Expo, or you can eject to use ExpoKit, which will allow you to continue using the Expo APIs. Read more about ejecting with CRNA here.

You probably need to follow this guide and use ExpoKit.

**Comment by MacKentoch** [comment]
I don't use Expo but this PR should be related.

**Comment by utsav-dholakia** [comment]
I tried and built the app using react-native and not using Expo and made it work. It seems Expo is not allowing me to do react-native link react-native-beacons-manager even after I detached the project from it where I should have been able to link the project to the app just like any other react-native init app.

**Comment by leocavalcante** [comment]
The problem here was that `link` didn't add `new BeaconsAndroidPackage()` to `getPackages`.

**Comment by MacKentoch** [comment]
@leocavalcante thank your helpful feedback.

Is that ok @haaslukas ?

**Comment by haaslukas** [comment]
@MacKentoch jep. thanks for the support
