### ISSUE TITLE
1.0.5 version is not published in npm

### ISSUE THREAD

**Issue by zoranmarjanovic** [MacKentoch/react-native-beacons-manager#37]
### Version
1.0.5

### Platform
iOS | Android

### Steps to reproduce
1.  run yarn add react-native-beacons-manager or npm install react-native-beacons-manager
2.  installed version is 1.0.4

### Expected behavior
It should install 1.0.5 version

### Actual behavior
install version is 1.0.4

**Comment by MacKentoch** [comment]
Hi,

v1.05 is not a released version yet.

If you want to install this version (master from GitHub) it is possible:
_npm install git+https://github.com/MacKentoch/react-native-beacons-manager.git_
