### ISSUE TITLE
Build fails on iOS with 1.0.5

### ISSUE THREAD

**Issue by jsyrjala** [MacKentoch/react-native-beacons-manager#38]
### Version
1.0.5 (version 1.0.4 is not affected)

### Platform
iOS

### OS version
MacOS

### Steps to reproduce
1.  Create a new project using `react-native init projectname`
2. Add `react-native-beacons-manager` and link it.
3. Add following to `index.ios.js`
```
import Beacons from 'react-native-beacons-manager'
```
4.  Start ios simulator `react-native run-ios`

### Expected behavior
iOS simulator should start without errors

### Actual behavior
iOS simulator starts and shows this error:
```
undefined is not an object  (evaluating 'beaconsAndroid.ARMA_RSSI_FILTER')

module.android.js:23:40
```

If I remove `module.android.js` file and all references to it, the build will work.

https://github.com/MacKentoch/react-native-beacons-manager/issues/28 seems to be related.

**Comment by MacKentoch** [comment]
Thank you @jsyrjala for this detailed issue.

That was very helpful.
I did not loose time going a wrong way to resolve it.

It is nearly related to #28 but the origin is more subtile / tricky.

It is due to a real mess with `ES6 import/export` in index.js and js modules files.
