### ISSUE TITLE
Is there Estimote sticker (nearables) support?

### ISSUE THREAD

**Issue by nkostop** [MacKentoch/react-native-beacons-manager#4]
Is there any nearable packet support?

**Comment by MacKentoch** [comment]
Hi @nkostop 

To be honest I didn't know Estimote stickers.

As there are iBeacon compatible ones on the Estimote website it should / must work the same.

I don't even have a real beacon, I just use [an iPhone transformed into a beacon](https://github.com/gemtot/iBeacon). 

It is the same (except I wouldn't leave my iPhone inside a room as I would with a beacon :smile:)

**Comment by MacKentoch** [comment]
I close this issue. 

Reopen it if I was wrong or did not understand.
