### ISSUE TITLE
Cannot build an android app

### ISSUE THREAD

**Issue by vandervidi** [MacKentoch/react-native-beacons-manager#41]
i want to mention that there is no code related to this library in the react native app

### Version
1.0.1

### Platform
Android

### OS version
 android 7.0

### Steps to reproduce
1.  npm install the module
2.  npm link it
3.  react-native run-android

### Expected behavior
Successful build

### Actual behavior
Build failure: 
error:
 package com.mackentoch.beaconsandroid does not exist
import com.mackentoch.beaconsandroid.BeaconsAndroidPackage;

cannot find symbol new BeaconsAndroidPackage(),

**Comment by MacKentoch** [comment]
Hi @vandervidi 

BeaconsAndroidPackage Is just the android class bridge.
But you should not even be heard about it.

v1.0.1 is pretty old release, despite there is no reason it does the behavior, would you mind trying with a newer version (I added fixes for android in later versions).

If it still occur, I will need more info, like RN version.

Thank you for submitting this issue we will soon fix it.

**Comment by MacKentoch** [comment]
I just published v1.0.7.

NOTE: RN 0.48 was buggy so better stick to 0.47.2 until it is fixed.

**Comment by vandervidi** [comment]
@MacKentoch Hi there, thank you for the fix and tips. I will test it later today.

**Comment by MacKentoch** [comment]
I close since related to old version.

re-open if needed.
