### ISSUE TITLE
RCTDeviceEventEmitter.emit - JSON object value was NaN or INF

### ISSUE THREAD

**Issue by franticBIT** [MacKentoch/react-native-beacons-manager#43]
### Version
1.0.4

### Platform
Android

### OS version
Android 7.1.2

### Steps to reproduce
I use [Beacon Simulator](https://play.google.com/store/apps/details?id=net.alea.beaconsimulator&hl=en) to simulate an iBeacon on a Pixel with the following settings:
* Tx power: 0
* Transmission Power: Medium

### Expected behavior
Beacon should be recognised when in range.

### Actual behavior
Error is thrown:  
![screenshot_20170905-160423](https://user-images.githubusercontent.com/7360440/30065262-8f8548dc-9254-11e7-9165-7540117e8aa3.png)

**Comment by MacKentoch** [comment]
Could you please update with lastest version of the librairie?

I added a couple of fixes for android since this version.
And I don't reproduce this issue on a real phone.

**Comment by MacKentoch** [comment]
I don't reproduce this issue on latest versions.

By the way, ensure to `react-native link`
