### ISSUE TITLE
regionDidEnter/regionDidExit not firing in background mode

### ISSUE THREAD

**Issue by beiming** [MacKentoch/react-native-beacons-manager#44]
### Version
1.0.7

### Platform
iOS 

### OS version

iOS 10

### React Native version
0.47.2

### Steps to reproduce
1.  **use background mode** check [this documentation](https://github.com/MacKentoch/react-native-beacons-manager/blob/master/BACKGROUND_MODES.md)
2. killed/sleeping app, wait 1 minute

### Expected behavior
should fire regionDidExit event, and print something

### Actual behavior
not fire regionDidExit, but beaconsDidRange is ok when app is foreground, and in background will print nothing.

I build a release package, install it to my device. when get regionDidEnter/regionDidExit/beaconsDidRange event, post data to my test api and save log.
like:

```
fetch('http://localip:3000/ibeacon', {...fetchOption, body: dataStr})
            .then(() => console.log('iBeacon ok'))
            .catch((error) => console.log('iBeacon error:', error))
```

**Comment by MacKentoch** [comment]
linked to #42

**Comment by MacKentoch** [comment]
[see](https://github.com/MacKentoch/react-native-beacons-manager/issues/42#issuecomment-330744741)

**Comment by beiming** [comment]
Hi, I found the root cause that define the region with out major and minor. 
just only 
```
const region = {
    identifier: 'XXXXXX',
    uuid: 'xxxxxxxxxx-x-xx--x-x-x-x-x-',
};

await Beacons.startMonitoringForRegion(region);

regionDidEnterEventListener = Beacons.BeaconsEventEmitter.addListener('regionDidEnter', (data) => onData('regionDidEnter', actionFunc, data));
......

```

Even more than I specified major, It will fire `regionDidEnter` and `regionDidExit`.

Now I want to know
Can I just specify identifier and uuid, then fire `regionDidEnter` and `regionDidExit` event?
Any official documents to explain it? (I found a long time did not find).

Why native code for `regionDidEnter` event body only contain `identifier` and `uuid` info?
```
-(void)locationManager:(CLLocationManager *)manager
        didEnterRegion:(CLBeaconRegion *)region {
  NSDictionary *event = @{
                          @"identifier": region.identifier,
                          @"uuid": [region.proximityUUID UUIDString],
                          };
    [self sendEventWithName:@"regionDidEnter" body:event];
}
```
Thanks. @MacKentoch
