### ISSUE TITLE
Expo [TypeError: undefined is not an object (evaluating 'BeaconsManager.requestAlwaysAuthorization')]

### ISSUE THREAD

**Issue by bab00n87** [MacKentoch/react-native-beacons-manager#47]
Hey guys I have problems with expo and react-native-beacons-manager. I used the same code on a blank project and it works without a problem. Just with expo I have this issue. 

### Version
1.0.1

### Platform
iOS | Android

### OS version
Version 10.13

iOS 10| android 7.0...

### Steps to reproduce
1.  created a new expo project
2.  followed the guideline for react-native-beacons-manager
3.  initialised beacon

CODE:

import React from 'react';
import { StyleSheet, Text, View, DeviceEventEmitter } from 'react-native';

import Beacons from 'react-native-beacons-manager';

export default class App extends React.Component {
  state = { beacon: false, proximity: 'wawawa', beaconRange: '', counter: 0};

  constructor(props) {
  super(props);
    // this.socket = SocketIOClient('http://192.168.0.23:3000');
    Beacons.requestAlwaysAuthorization();
    this.beaconsDidRangeEvent = null;
    this.region= {
      identifier: 'Estimotes',
      uuid: 'CDC19275-FBC7-4E69-A28E-42CD874598123'
    }
  }
  componentWillMount() {
Beacons.requestAlwaysAuthorization();
// Beacons.startRangingBeaconsInRegion(region);
Beacons.startMonitoringForRegion(this.region)
.then(() => console.log('Beacons monitoring started succesfully'))
.catch(error => console.log(`Beacons monitoring not started, error: ${error}`));
Beacons.startRangingBeaconsInRegion(this.region)
.then(() => console.log('Beacons ranging started succesfully'))
.catch(error => console.log(`Beacons ranging not started, error: ${error}`));

Beacons.startUpdatingLocation();

  }

### Expected behavior
Should start beacon request. 

### Actual behavior
[exp] [TypeError: undefined is not an object (evaluating 'BeaconsManager.requestAlwaysAuthorization')]

**Comment by bab00n87** [comment]
Could it be a problem with react 16?

**Comment by MacKentoch** [comment]
I'm sorry this library does not support expo.

You need to eject to make it work.

**Comment by candytrickster** [comment]
Hi, I have the same problem. Same stuff and everything but I already ejected to expokit and still get that same error. Any advice?

**Comment by andreassavva** [comment]
I have the same issue with 1.0.7. I used `react-native init`, so no Expo whatsoever.

**Comment by thibauttoguekam** [comment]
I hava the same issue with 1.0.7 I used rect-native init and still get that same error. solution please?

**Comment by sfratini** [comment]
I was having this problem and this is due to something missing in the documentation. Those permission requests functios are specific for iOS. In Android those do not exist. You just need to enable location permission either manually or with some other module.

**Comment by Yara-the-devil-princess** [comment]
Yup ..I tried that too..I add location permission..Could you explain much
more..how you will detect beacon when app is killed ?..

**Comment by sfratini** [comment]
So, with the basic react native project I went into App Settings in the Android system, and I enabled the location permission. After that, the beacons were detected by the module. 

If you have the app running in foreground or in background (meaning, not killed) everything works as expected. 

What I did for the killed app, is I send a push notification with firebase (It has to be a data message sent i high priority so the app can read it) and then I start my app activity. If I see the information is not being sent, I push a message that tells the app to start itself. For my use case it works. It would be best if I could start the activity in background but I havent found how. 

Check react-native-firebase (messaging module) and react-native-startApp

**Comment by sfratini** [comment]
@Yara-the-devil-princess In your particular case I would suggest doing an Android Native Modular for React Native, where you make a service that could run in the background. That would mean basically that you mostly dont use RN for this processing. 

Also, if you get a crash from background to foreground, see how you are starting the Activity or the app. I had a crash doing Activity.startActivity() but my push worked for the app even in killed state by starting the activity from the react context. Something like getReactApplicationContext().startActivity()

**Comment by Yara-the-devil-princess** [comment]
Thank you once again..I m new to this..so I need to learn how to make new
Android module for me..Thank you for suggestions .

**Comment by soundaryad10** [comment]
@sfratini As you said, I move to firebase and i created google-services
files.But i get [ > Could not resolve all dependencies for configuration
':app:_debugApk'.
   > A problem occurred configuring project ':react-native-fcm'.  >
java.lang.NullPointerException (no error message) ] Sorry to bother you. I
am using react-native fcm to send my Messaging module.

**Comment by Alfredo-Delgado** [comment]
cf. https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/LocationAwarenessPG/CoreLocation/CoreLocation.html

**Comment by hadpro24** [comment]
> I'm sorry this library does not support expo.
> 
> You need to eject to make it work.

I have got the same problem, with expo 37 eject... in android device. I don't know why you close this issues... I not see the any solution with it.

Thanks, I need help :-)
