### ISSUE TITLE
iOS not working Exception 'Invalid parameter not satisfying: region != nil' was thrown

### ISSUE THREAD

**Issue by stoneman1** [MacKentoch/react-native-beacons-manager#5]
Hello,

Having this problem with iOS, for Android everything is working fine :
[fatal][tid:com.facebook.react.RNiBeaconQueue] Exception 'Invalid parameter not satisfying: region != nil' was thrown while invoking startRangingBeaconsInRegion on target RNiBeacon with params (
        {
        identifier = laa;
        uuid = xxx;
    }
)

**Comment by stoneman1** [comment]
Actually got it working. The UUID  has to be in correct syntax like this : 
xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

**Comment by MacKentoch** [comment]
Hi @stoneman1 

Glad you solved.

**Comment by ShaileshPrajapati-BTC** [comment]
Having this problem with iOS, for Android everything is working fine :
[fatal][tid:com.facebook.react.RNiBeaconQueue] Exception 'Invalid parameter not satisfying: region != nil' was thrown while invoking startRangingBeaconsInRegion on target RNiBeacon with params (
{
identifier = laa;
uuid = 32445EWG-FREF-4565-6KJF-JJ8899000098 ;
}
)
