### ISSUE TITLE
Warning: Sending event with no listeners registered

### ISSUE THREAD

**Issue by eurobob** [MacKentoch/react-native-beacons-manager#50]
### Version
1.0.7

### Platform
iOS | Android

### OS version

iOS 10| android 7.0...

### Steps to reproduce
1.  Any usage of the code

### Expected behavior
Package should work without warnings

### Actual behavior
Warnings are displayed in YellowBox for all events:
- Sending `authorizationStatusDidChange` with no listeners registered.
- Sending `didDetermineState` with no listeners registered.
- Sending `regionDidEnter` with no listeners registered.
- Sending `regionDidExit` with no listeners registered.
- Sending `beaconsDidRange` with no listeners registered.

**Comment by eurobob** [comment]
Nevermind, I was accidentally pulling in the master branch as a side effect since the time when 1.0.5 was not available on npm

**Comment by eurobob** [comment]
I'm reopening this issue as something doesn't seem to be right since the BeaconsEventEmitter addition from @ashemah 

Even when I add the listeners before running any other beacon related methods I still get these warnings.

**Comment by drailanjohngss** [comment]
I'm getting an error using BeaconsEventEmitter, but when I use the DeviceEventEmitter i'ts working but no beacons are detected.

**Comment by JBrown313** [comment]
Having the same problem as @drailanjohngss DeviceEventEmitter runs with no errors but does not fire the listeners while BeaconsEventEmitter is undefined.

**Comment by dittmarconsulting** [comment]
```
"react": "16.3.1",
"react-native": "0.55.4",
"react-native-beacons-manager": "github:MacKentoch/react-native-beacons-manager",

Xcode: 10
iOS: 12
iPhone 8: physical device
```

I'm having the same issue. Getting the YellowBox warning `Sending `authorizationStatusDidChange` with no listeners registered.`, although the listener has been initialised

```
componentDidMount(){
        // listen to authorization change
        this.authStateDidRangeEvent = Beacons.BeaconsEventEmitter.addListener(
            'authorizationStatusDidChange',
            info => console.log('authorizationStatusDidChange: ', info)
        )
        // listen to iBeacons that enter the region
        this.regionDidEnterEvent =
            Beacons.BeaconsEventEmitter.addListener('regionDidEnter', data => {
                console.log('****** MONITORING - regionDidEnter data: ******', data);
                const time = moment().format(TIME_FORMAT)
                this.setState({
                    regionEnterDatasource: this.state.rangingDataSource.cloneWithRows([
                        {
                            identifier:data.identifier,
                            uuid:data.uuid,
                            minor:data.minor,
                            major:data.major,
                            time
                        }
                    ])
                })
            })
}
``` 
The `iBeacon` I have in the region never show up and I never see the listener message `****** MONITORING - regionDidEnter data: ******`

**Comment by sjaidka224** [comment]
Did this work for you guys? I am having the same issue. Please help!

**Comment by iamandiradu** [comment]
I'm also having this problem (iOS). Killed app is awakened by entering the region (activating the beacon), but the listener is not attached to the event. Tried putting the listener in componentWillMount - same result. Anyone knows a working branch/version of this library for iOS? 
Works fine if the app is active or in background.

**Comment by iamandiradu** [comment]
I'm working on a way to store the beacon data if no listeners are registered and a method to retrieve the data. Maybe this'll work.

**Comment by iamandiradu** [comment]
I've forked @newoceaninfosys' fork and added the 'missed beacon' method. Check my last 3 commits for how to replicate it. Use it by adding this in your didMount function:
```
if (Platform.OS === 'ios') {
                // iOS cold start listener
                this.beaconMissedListener = Beacons.BeaconsEventEmitter.addListener(
                    'onMissedBeacon',
                    data => {
                        if (data) {
                            this._beaconListener(data);
                        }
                    },
                );

                Beacons.getMissedBeacon();
            }
```

**Comment by iamandiradu** [comment]
@MacKentoch, could this be a feature of the library? Storing 'lost' beacons for retrieval when the app is fully loaded?

**Comment by RM-Eric** [comment]
Try Beacons.BeaconsEventEmitter.addListener

**Comment by iamandiradu** [comment]
I made a fork and implemented the 'beacon store' myself. :)

**Comment by organom** [comment]
> I made a fork and implemented the 'beacon store' myself. :)

The fork looks very nice, works perfectly in iOS, but somehow the beacon detection is not working in Android.

**Comment by iamandiradu** [comment]
Sorry, I can't help you on this right now. I'm focusing on finishing my studies.
I abandoned the project several months ago and forgot what's in there. :(

**Comment by organom** [comment]
Thanks for the fast reply. No worries, I will handle it and try to get to a fix against the current master.
