### ISSUE TITLE
Queation/Bug: getting “Sending `beaconsDidRange` with no listeners registered.”

### ISSUE THREAD

**Issue by oferRounds** [MacKentoch/react-native-beacons-manager#51]
I followed the example as is, and everything worked great.

But suddenly, I stopped getting the Beacons detection event, while getting the warning:
“Sending beaconsDidRange with no listeners registered.”

Any idea what might cause this? I’ve tried everything...

I do have the code part:
```
var subscription = DeviceEventEmitter.addListener(
  'beaconsDidRange',
  (data) => {
       console.log(data);
  }
);
```

### Version
master

### Platform
iOS

### OS version
iOS 11.02

### Steps to reproduce
As in the example

**Comment by oferRounds** [comment]
Ok, it turns out that the version on master not working well - reverting back to 1.0.7 made it working again.

Ref: https://github.com/MacKentoch/react-native-beacons-manager/issues/48

**Comment by MacKentoch** [comment]
Sorry, I forgot to mention the recent breaking change in 1.0.8 (see [CHANGELOG](https://github.com/MacKentoch/react-native-beacons-manager/blob/master/CHANGELOG.md#108-coming-soon--still-in-master)):

```javascript
    // before 1.0.8 (or until 1.0.7):
    DeviceEventEmitter.addListener()
    // simply becomes (for both iOS and Android)
    Beacons.BeaconsEventEmitter.addListener()
    ``` 

That is why it did not work as in your example you still use `DeviceEventEmitter`.

**Comment by MacKentoch** [comment]
I will update versioning since it has no more sense keeping 1.0.x whit so many changes.
