### ISSUE TITLE
iOS not working Exception 'Invalid parameter not satisfying: region != nil' was thrown

### ISSUE THREAD

**Issue by ShaileshPrajapati-BTC** [MacKentoch/react-native-beacons-manager#52]
### Version
1.0.7

### Platform
iOS

### OS version

iOS 10

### Steps to reproduce
1.  when calling startMonitoringForRegion() method
2.  with uuid: 32445EWG-FREF-4565-6KJF-JJ8899000098

### Expected behaviour
it should not raise this exception even though uuid format is correct

### Actual behaviour
App crashing when passing this uuid

**Comment by MacKentoch** [comment]
Hi @ShaileshPrajapati-BTC 

It appears that this error is right.

You UUID is not a valid UUID.

Please check this [UUID online tester](http://guid.us/Test/GUID) it always matches mine when I have a doubt.

*NOTE: I'm not affiliated with this website I just discovered thank to our friend Google Search.*

**Comment by ShaileshPrajapati-BTC** [comment]
@MacKentoch but it should return a some message not "Invalid parameter not satisfying: region != nil' was thrown" it's crashing my app and not able to even catch this error in RN.

**Comment by a2zcreatorzTeam** [comment]
getting same issue
