### ISSUE TITLE
Scan when app is killed

### ISSUE THREAD

**Issue by juanmanuelarze** [MacKentoch/react-native-beacons-manager#6]
### Version
1.0.1

### Platform
Android

### OS version

android 6.0.1...

### Expected behavior
The app continue detecting beacons even if app is killed

### Actual behavior
The scan stops when app is killed

**Comment by MacKentoch** [comment]
react-native-beacons-manager is based on altBeacon for android.

altBeacon should give expected behaviour. 

I suppose it is linked in some way to this [stackoverflow](http://stackoverflow.com/questions/42386538/altbeacon-android-beacon-library-not-working-when-app-is-killed)

**Comment by MacKentoch** [comment]
I've just finish fixing some bugs and documenting iOS side.

I will now start android and fix this issue, so that android will have same amount of docs: [here iOS](https://github.com/MacKentoch/react-native-beacons-manager/tree/master/examples/samples)

**Comment by MacKentoch** [comment]
Alright, it seems like stackoverflow upper link is dead... RIP

All I'm sure is that it is ok when app is in background on Android (and iOS).

When app is killed is another subject.
I would go deeper in android native if I really needed it.

But for my concern when I close an application I want it to be closed once and for all at least to save ma battery.

Anyway if someone is more bullet proof in Android native dev I opened to information/suggestion about that.

**Comment by juanmanuelarze** [comment]
Hello, I could not make the application scan after being killed with this wrapper, but I could do it with the native library directly, for the use of this feature it is necessary to add some lines of code in MainApplication.java, that is the reason why I could not make it work with this wrapping, so your work is great.
But the work I needed to do was a bit more complicated, but finally with the editing of some beacon android library codes I could make the application range beacons even killed

**Comment by MacKentoch** [comment]
@juanmanuelarze Thank you for sharing it.

**Could you share or give a link to what kind of native code is needed in `MainApplication.java` to make it work like you did?**

You can even PR some kind example ([like these](https://github.com/MacKentoch/react-native-beacons-manager/tree/master/examples/samples)) if you prefer.

**Comment by juanmanuelarze** [comment]
read the docs https://altbeacon.github.io/android-beacon-library/samples.html

**Comment by MacKentoch** [comment]
So evident I did not even think of Albeacon docs :+1 @juanmanuelarze

**Comment by r-bansal** [comment]
@MacKentoch - Should we update this library to allow for monitoring to occur *when app is killed in Android* as a default to be consistent with iOS? I still do not see this working given the current rn-beacon-manager.

Monitoring only works on Android when the app is in background/foreground, not when app state is killed. Let me know if I am wrong, or missed some part of the documentation.

If everyone has to go through and configure as per @juanmanuelarze comment to be consistent with iOS implementation (i.e. local notification when app is killed or in background), it will be useful to have in the lib.

**Comment by andreassavva** [comment]
@juanmanuelarze can you give the code you used to do it? I have implemented the solution but still does not work.

**Comment by helloagain-dev** [comment]
Do you guys think it is even possible to wake up the App from the background?

**Comment by eurobob** [comment]
@juanmanuelarze Could you elaborate on your solution? What you have said in the comment above does not make any sense

**Comment by longpro1601** [comment]
@juanmanuelarze please help me for Scan when app is killed.
Thanks.

**Comment by Yara-the-devil-princess** [comment]
@juanmanuelarze Can you provide some guidance for scan when app is killed .

**Comment by Najeisleem** [comment]
@juanmanuelarze Can you provide some guidance for scan when app is killed .

**Comment by JayricMok** [comment]
@juanmanuelarze Can you provide some guidance for scan when app is killed ?

**Comment by lunoware** [comment]
Can you provide some guidance for scan when app is killed ?

**Comment by RM-Eric** [comment]
I agree with everyone calling for some examples of the code that should be added, perhaps this issue should be re-opened? Many people are still having problems with it

**Comment by RANGELJ** [comment]
@juanmanuelarze Can you provide some guidance for scan when app is killed ?

**Comment by juanmanuelarze** [comment]
@RANGELJ first of all, you cant do this from react native, you need know android and make this with java, and send event through DeviceEventEmitter.
Read this docs: https://altbeacon.github.io/android-beacon-library/samples.html
Don't use this lib, use the native library directly, and do the modifications i mentioned before.

**Comment by RANGELJ** [comment]
Thanks @juanmanuelarze

**Comment by juanmanuelarze** [comment]
@RANGELJ the native lib support monitoring when is killed but doesn't support ranging when is killed, i do this a lot of years ago, and i have no need of do it again. 

Copy RegionBootstrap.java from android-beacon-lib into your project and replace startMonitoring functions for startRanging functions, in the docs of the android bec. lib. tolds you to paste some code in MainActivity for startMonitoring functionality, in that code replace the regionBootstrap.java of the lib for yours copied before.

**Comment by RANGELJ** [comment]
My plan is to use the monitoring when killed, and when awaken, i use a quick range to get specific beacons. So your description is just what I need, if everything goes to plan I will let you all know. Thanks again @juanmanuelarze

**Comment by Najeisleem** [comment]
@juanmanuelarze I'm using the native android app with android-beacon-library , but when you kill the app and wait for 15 to 30 min there is no detection beacons anymore and maybe detect after entering region and wait for 5-8 min to detect, any idea to detect beacons every second and not stopping?
sorry for bad English

**Comment by juanmanuelarze** [comment]
@Najeisleem i work with this lib a few years ago but cat remember that RegionBootstrap.java have a variable for scan time. Also, if you are ranging beacons, the app detects when enter into a region only, if you are monitoring, can detect almost time. You can do what i mentioned before about copy RegionBootrap.java and edit the code as your need for example the time interval of ranging or monitoring. Don't forget change the RegionBootstrap.java of the original lib that initialize in your MainActivity.java for yours.
