### ISSUE TITLE
Question/ Bug: Beacon is not detected on Android

### ISSUE THREAD

**Issue by oferRounds** [MacKentoch/react-native-beacons-manager#61]
### Version
1.0.7

### Platform
Android

### OS version
Android 7.0...

### Steps to reproduce
```
Beacons.detectIBeacons()
try {
     Beacons.startRangingBeaconsInRegion(region)
     console.log(`Beacons ranging started successfully!`)
} catch (error) {
     console.log(`Beacons ranging not started, error: ${error}`)
}
```
- **Both Location and Bluetooth services are on.**

### Expected behavior
Beacon should be detected.

### Actual behavior
Beacon is not detected :/ (it does work on iOS).
Is there anything else I need to do? Do I need to ask for Location permission?

**Comment by eurobob** [comment]
Could be a device issue? Have you tried using the ```checkTransmissionSupported``` method?

**Comment by oferRounds** [comment]
Thanks! It’s not a device issue, as using the Estimote app, I see that the device does detect the beacon. 
Could be related to any permission issue? I am an iOS developer – new to Android – so I encountered some posts about location permission.

Is the above code is all needed basically?

**Comment by oferRounds** [comment]
`checkTransmissionSupported` returns: `SUPPORTED`

**Comment by oferRounds** [comment]
Ok, I had some progress: it seems that problem is with listening to`regionDidEnter`, which is not get called. In oppose to `beaconsDidRange` which does get called. Perhapas the name of the event is different on Android?

**Comment by oferRounds** [comment]
Perhaps I need request permission for that?

**Comment by oferRounds** [comment]
My mistake! 😯 I called `startRangingBeaconsInRegion:` instead of `startMonitoringForRegion:`...
Really sorry for that! :)

**Comment by MacKentoch** [comment]
Glad you fixed
