### ISSUE TITLE
iOS Beacon signal strength not shown

### ISSUE THREAD

**Issue by eduplus** [MacKentoch/react-native-beacons-manager#7]
### Version
1.0.1

### Platform
iOS

### OS version

iOS 10.2.1.

### Steps to reproduce
1. Location and Bluetooth LE enabled from XCode
2. Code: 

const region = {
      identifier: 'laa',
      uuid: '1596c947-686f-cc35-c9ba-932320a0cce8'
    }
    Beacons.requestWhenInUseAuthorization();
    Beacons.startRangingBeaconsInRegion(region);
    Beacons.startUpdatingLocation();

### Expected behavior
Get beacon data with signal strength

### Actual behavior
Beacons are coming with the data, but rssi is 0 and accuracy -1

Example:

{"beacons":[{"major":1,"minor":0,"uuid":"1596C947-686F-CC35-C9BA-932320A0CCE8","accuracy":-1,"rssi":0,"proximity":"unknown"}

Beacons are iBKS+ beacons and can get signal strength correctly from these beacons using Android with this library.

**Comment by MacKentoch** [comment]
Thank you for the issue.

The only I'm sure right now (*without being able to debug*) is that the v1.0.2 won't change anything to this issue.

That is already a satisfaction to be sure of something 😄

**Comment by MacKentoch** [comment]
@eduplus I thought I would have same behaviour as you but it works as expected **UNLESS** I downgrade the emission power of the beacon (I used a simulator).

**Let me give you more details on my test:**

```json
	"dependencies": {
		"react": "~15.4.0",
		"react-native": "0.41.2",
		"react-native-beacons-manager": "1.0.1",
		"react-native-bluetooth-state": "^2.0.0"
	}
```

*Note: I just manually forced react-native version (to get rid of potential influence of the newer version 0.42) with:*
```bash
react-native init --version "0.41.2" my-app-for-debug
```

Then to test an ibeacon like yours `I used a trick`: [beacon simulator on android](https://play.google.com/store/apps/details?id=net.alea.beaconsimulator&hl=fr)
This beacon simulator is awesome (*if you have an android device*), I created a beacon:

I chose a beacon type: **iBeacon**, with beacon settings:
- uuid: '1596c947-686f-cc35-c9ba-932320a0cce8'
- major: 1
- minor: 0
- `txPower: -65 dB`

and broadcast settings (*as default I did not touch them)*:
- transmission power: Medium ~66dBm
- Frequency Mode: Balanced ~3 Hz

**playing with txPower:**
- when > -100dB it seems like it is ok but long lasting to refresh
- when < -100dB it becomes less precise and at -120dB it doesn't work well

I suspect you ibeacon power is too low?

**Comment by eduplus** [comment]
Thank you for testing this. I tested with Beacon Simulator and I am getting signal strength now. It might be due to the real beacons configuration, that they are sending eddystone as well, so maybe that interferes somehow. Will have to check on Monday. Seems that it is on our beacon config and not the library, so this probably can be closed.

**Comment by MacKentoch** [comment]
Alright so I close.

Re-open this issue if needed.

**Comment by eduplus** [comment]
Just to comment what was causing the issue for me: iBKS has calibrated power estimate at 1m. For some reason value there was 4. I changed it to -58 as I saw in some examples, and iOS started showing rssi strength again. Thanks for the help.

**Comment by MacKentoch** [comment]
Thank you too @eduplus for taking time giving a feedback and for your helpful contribution
