### ISSUE TITLE
empty array on scanning beacons 

### ISSUE THREAD

**Issue by akshaypm** [MacKentoch/react-native-beacons-manager#74]
hey guys when i am trying to scan the beacon from android device. When i write a stand alone app it works fine and detection is working but i am integrating the library and writing the code in enterprise project folder array of beacons is empty all the time may i know how to get rid of this? 
 i went through issue #14 but no use

**Comment by akshaypm** [comment]
need to turn on all permission in android and its working fine

**Comment by bab00n87** [comment]
> need to turn on all permission in android and its working fine

what does "all" mean?
