### ISSUE TITLE
iOS App rejected due to background permissions

### ISSUE THREAD

**Issue by petecoop** [MacKentoch/react-native-beacons-manager#8]
Hey have just used this library for an app and it's worked really great. But I'm now stuck on the app review process, I've had the following back from Apple:

>Specifically, because iBeacon entry and exit notifications are provided by the OS to the app, the app itself does not require background location or bluetooth for this feature to function. 
>
>It would be appropriate to remove background location and bluetooth from this app’s required background modes section of the Info.plist before resubmitting for review.

Should this work without the background modes?

**Comment by MacKentoch** [comment]
Hi @petecoop 

I've never push to appStore an application that uses my library or the one it comes from.

Do you really need background mode?
- If not you can disable entire background modes
- otherwise, I suggest you test your application and check [original iOS library instructions concerning background modes](https://github.com/frostney/react-native-ibeacon#background-mode)

Apple review can be sometimes frustrating at 1st point of view.

But it makes iOS and iOS dev better and from my experience they are nice when you ask for more details

**Comment by petecoop** [comment]
Ah I assumed it was needed as in your docs it says:
>IMPORTANT: you have to set Bluetooth and localization service in background Modes

I'll test without and see if it still works and re-submit.

Yeah it is fairly frustrating waiting days to go through submission, whilst the Android version went up almost instantly. I have worked with much worse tbh (Samsung Smart TV)

**Comment by MacKentoch** [comment]
Yes as far as I remember it was before (*I mean last year when I used beacon in react native for 1st time then wrote an article*).

My apologise I need to update README.

This lib is so young it is difficult to be faster to make it completely clear and nice.

My priories were to make it working on both iOS and Android (*it comes from a merge between 2 different repos*).

**Anyway thank you for the issue and pointing out this.**

**Comment by petecoop** [comment]
Yeah that makes sense, and thanks I needed to have something that worked on both iOS and Android and this has worked really nicely.

I've now rebuilt and re-submitted to the app store, so shall see what the next issue is, hopefully not beacon related!

**Comment by eurobob** [comment]
Did your new binary get approved @petecoop?

**Comment by MacKentoch** [comment]
As related to this issue, I'm improving documentation it will be code samples + detailed explanations like [ranging on iOS](https://github.com/MacKentoch/react-native-beacons-manager/blob/master/examples/samples/ranging.ios.md).

**Comment by petecoop** [comment]
Hey, yeah the app was finally approved after removing these background modes. thanks for your help

**Comment by MacKentoch** [comment]
@petecoop glad to hear that 👍
