### ISSUE TITLE
Undefined is not a function

### ISSUE THREAD

**Issue by sandropoluan** [MacKentoch/react-native-beacons-manager#80]
### Version
1.0.7

### Platform
 Android

### OS version

android 5.0...

I got this error when try to run this code
```
var region = { identifier:'Estimotes', uuid:'fda50693-a4e2-4fb1-xxxx-xxxxxxxx' };
Beacons.detectIBeacons();
Beacons.requestWhenInUseAuthorization();

Beacons.startMonitoringForRegion(region);
Beacons.startRangingBeaconsInRegion(region);
			
Beacons.startUpdatingLocation();

```
This module already linked.
I have check it manually 

in **settings.gradle**
```
include ':react-native-beacons-manager'
project(':react-native-beacons-manager').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-beacons-manager/android')
``` 

**app/build.gradle**
`compile project(':react-native-beacons-manager')`

in **MainApplication.java**
`import com.mackentoch.beaconsandroid.BeaconsAndroidPackage;`
and
`new BeaconsAndroidPackage(),`

**Everything is there**. There something I miss?

![screenshot_2018-03-19-17-24-52-276_com eabsenglobalindonesia eabsenmobile](https://user-images.githubusercontent.com/11922251/37587666-f251912a-2b9a-11e8-97d5-cbce7d1fa047.png)

**Comment by dukhanov** [comment]
Hi, It is an illegal method for Android platform `requestWhenInUseAuthorization`

**Comment by MBach** [comment]
Code should be identical on both platforms, and mocked by:

    requestWhenInUseAuthorization: () => { console.log('not used on Android') }

**Comment by MacKentoch** [comment]
Android and iOS aren't the same platform.

Mocking methods and property to give illusion of being identical leads to code smell.

Please read the [detailed-documentation](https://github.com/MacKentoch/react-native-beacons-manager/tree/master/examples/samples#detailed-documentation--sample-code)
