### ISSUE TITLE
Android 8.1 background scanning returns no results

### ISSUE THREAD

**Issue by timsatterfield** [MacKentoch/react-native-beacons-manager#82]
### Version
1.0.7

### Platform
Android

### OS version

android 8.1

### Steps to reproduce
1.  app in background
2. be ranging beacons

### Expected behavior
Should detect beacons and return results in didBeaconsRange

### Actual behavior
No beacon data is delievered

This is due to the OS version and AltBeacon/android-beacon-library#637

I have opened a PR to pickup the altbeacon fix https://github.com/MacKentoch/react-native-beacons-manager/pull/81

**Comment by divye11** [comment]
Ranging does not work in background I guess. Try monitoring

**Comment by timsatterfield** [comment]
Um, like I said, this is an AltBeacon issue with android 8.1 and has been fixed there. See pull request #81.
