### ISSUE TITLE
regionDidExit & regionDidEnter not firing on iOS

### ISSUE THREAD

**Issue by r-bansal** [MacKentoch/react-native-beacons-manager#9]
### Version
1.0.1

### Platform
iOS

### OS version

iOS 10

### Steps to reproduce
1.  Follow Android example
2.  call Beacons.startMonitoringForRegion(region)
3.  add listeners

### Expected behavior
Events fires similar to Android (some delay) for entering/existing a region.

### Actual behavior
No events are firing.

**Comment by MacKentoch** [comment]
Hi @r-bansal 

Thank you for the issue.
I will fix that.

**Comment by fannedalk** [comment]
I'm having the same problem with Android. Did you get it to work with Android @r-bansal?

The beacon monitoring is started successfully but the event won't trigger:
DeviceEventEmitter.addListener('beaconsDidEnter', (data) => {
         console.log('beaconsDidEnter')
         console.log(data)
       })

**Comment by r-bansal** [comment]
@MacKentoch many thanks for the quick reply, any idea as to when a PR will be up? Just curious why it was not working?

**Comment by r-bansal** [comment]
@fannedalk - you need to listen for the correct events so `regionDidEnter` and `regionDidExit`, it works fine on Android.

**Comment by MacKentoch** [comment]
@r-bansal it won't be a PR but a new release.

I don't know. I'm still investigating.

But I can tell you it is the same issues as the original lib.
For example 
- [#48](https://github.com/frostney/react-native-ibeacon/issues/48) 
- or [#40](https://github.com/frostney/react-native-ibeacon/issues/40)

**Comment by MacKentoch** [comment]
As we discovered with the huge help from @r-bansal (*thank you*), iOS monitoring has constraints if you want it.
If I were a newcomer to beacon technology and iOS I would be lost.

I want it accessible / easy to understand and use so I'm preparing a huge improvement in the documentation / examples.

**Comment by MacKentoch** [comment]
fixed in v1.0.4.
