### ISSUE TITLE
iOS Build React/RCTBridge.h file not found

### ISSUE THREAD

**Issue by robertobrogi** [MacKentoch/react-native-beacons-manager#92]
### Version
1.0.7

### Platform
iOS

### OS version

iOS 11

### Steps to reproduce
1.  expo detach
2.  react-native link react-native-beacons-manager
3. pod install
4.  open xcode build

hi All,
i have a problem with Xcode project... is an expo detach project and in android work all fine in iOS I have this error:

'React/RCTBridge.h' file not found

![schermata 2018-04-18 alle 16 10 21](https://user-images.githubusercontent.com/34241295/38937331-43d8b632-4323-11e8-92f1-c012757ee399.png)

whats wrong?

**Comment by MacKentoch** [comment]
Check your profile.
But as you link the library why did you post install then?

Pod is tricky with React-Native, if you can avoid it it is better.

**Comment by MacKentoch** [comment]
You may need to read [about it](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies)

Ensure having React dep declared if you need pod:

```ruby
  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
```

**Comment by robertobrogi** [comment]
my step are:

1. npm install (my dependencies)
2. exp detach
3. go to iOS folder and pod install
4. react-native link react-native-beacons-manager
5. build my Xcode project

**Comment by robertobrogi** [comment]
not have idea :(

**Comment by robertobrogi** [comment]
I try to remove:

#import <React/RCTBridge.h>
#import <React/RCTConvert.h>
#import <React/RCTEventDispatcher.h>

(i find this solution in iBeacon git issues) 

but nothing....

there is any solution for the iOS project?

thanks

**Comment by robertobrogi** [comment]
I try:

in manage schema:

- remove parallel build
- in RNiBeacon taget scema I try to add react library
- in RNiBeacon target - build phases - link binary with libraries - add libReact.a

but nothing.... 

whats wrong!?

**Comment by robertobrogi** [comment]
any help? not have solution in ios.... :(

**Comment by robertobrogi** [comment]
@donedgardo have you find a solution?

**Comment by farzd** [comment]
@robertobrogi 

https://forums.expo.io/t/how-do-i-manually-add-pods-headers-public-to-the-header-search-paths-configuration/2427

**Comment by GeekChao** [comment]
> @robertobrogi
> 
> https://forums.expo.io/t/how-do-i-manually-add-pods-headers-public-to-the-header-search-paths-configuration/2427

Hi, I already added the relative path of 'react-native-beacons-manager' to 'Pods/Headers/Public' in Header Search Paths configuration. But it still has 'React/RCTBridge.h file not found' error. 
I would very appreciate that if you could share some insights. Thank you.

Environment: "react-native": "0.60.5"

![image](https://user-images.githubusercontent.com/10861987/63284275-2ba03480-c281-11e9-93e4-9a8c36dabaa4.png)

**Comment by nandorojo** [comment]
This issue is still happening for me. Has anyone found a fix?

**Comment by ThierryVC** [comment]
`react-native link react-native-beacons-manager`
Should add 
`pod 'ReactNativeBeaconsManager', :path => '../node_modules/react-native-beacons-manager'`
to your podfile. If it did't, try adding it manually or unlinking and relinking the module again and
then running pod install. This fixed it for me. I am on Master (1.1.0)

**Comment by LuLuSaBee** [comment]
Is there any solution about iOS Build React/RCTBridge.h file not found?

**Comment by mattia-beta** [comment]
> `react-native link react-native-beacons-manager`
> Should add
> `pod 'ReactNativeBeaconsManager', :path => '../node_modules/react-native-beacons-manager'`
> to your podfile. If it did't, try adding it manually or unlinking and relinking the module again and
> then running pod install. This fixed it for me. I am on Master (1.1.0)

Not working for me, it says:
_No podspec found for `ReactNativeBeaconsManager` in `../node_modules/react-native-beacons-manager`_

**Comment by iSaBo96** [comment]
Have anyone a solution for this? I have the same error in react-native 0.70.6

**Comment by Dawood448** [comment]
/node_modules/react-native-beacons-manager/ios/RNiBeacon/RNiBeacon/RNiBeacon.m:11:9: 'React/RCTBridge.h' file not found

#import <React/RCTBridge.h>
        ^~~~~~~~~~~~~~~~~~~
        
        
        same issue 
          "react-native": "0.68.2",
ruby-3.2.1
